- alias: Exterior Brighten
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -5
  condition: 
    - condition: state
      entity_id: group.exterior
      state: 'on'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 0
  action:
    service: light.turn_on
    entity_id: 
      - light.front_door
      - light.front_floods
      - light.rear_floods
    data:
      brightness: 254
      transition: 60
