- alias: Exterior Front - Brighten
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -5
  action:
    service: light.turn_on
    entity_id: light.front_door
    data:
      brightness: 254
      transition: 60
