- alias: Exterior Brighten
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -5
  condition: 
    - condition: state
      entity_id: group.exterior
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness: 254
        transition: 60
    - service: light.turn_on
      entity_id: 
        - light.front_floods
        - light.rear_floods        
