- alias: Exterior - Brighten
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -5
  action:
    service: light.turn_on
    entity_id: 
      - light.front_door
      - light.front_floods
      - light.rear_floods
    data:
      brightness: 254
      transition: 60
