- alias: Exterior Front Dawn
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 8
  condition: 
    condition: template
    value_template: '{{ states.binary_sensor.rain.state == "off" }}'
  action:
    - service: automation.turn_off
      entity_id: automation.exterior_front_dim
    - service: light.turn_off
      entity_id: light.front_door
      data:
        transition: 180
    - service: light.turn_off
      entity_id: 
        - light.front_floods
        - light.rear_floods
    - service: switch.turn_off
      entity_id: switch.patio_lights
