- alias: Exterior Front - Dawn
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5
  action:
    service: light.turn_off
    entity_id: 
      - light.front_door
      - light.front_floods
      - light.rear_floods
    data:
      transition: 60
