- alias: Exterior Front - Dawn
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.virtually_dark
    to: 'off'
  action:
    - service: automation.turn_off
      entity_id: automation.exterior_front__dim  
    - service: light.turn_off
      entity_id: 
        - light.front_door
      data:
        transition: 180
    - service: light.turn_off
      entity_id: 
        - light.front_floods
        - light.rear_floods
        - light.patio_lights
