- alias: Exterior Front Dim
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: light.turn_on
      entity_id:  
        - light.frontdoor
        - light.front_floods
        - light.rear_floods
      data:
        brightness: 100
        transition: 15      
    - service: switch.turn_off
      entity_id: switch.patio_lights
