- alias: Exterior Front Dim
  hide_entity: True
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: automation.turn_on
      entity_id: automation.exterior_front_dim
    - service: light.turn_on
      entity_id:  
        - light.front_door
        - light.front_floods
        - light.rear_floods
      data:
        brightness: 100
        transition: 300      
    - service: light.turn_off
      entity_id: light.patio_lights
