- alias: Exterior Front - Dusk
  hide_entity: True
  trigger:
    platform: time
    after: '00:00:00'
  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness: 100
        transition: 300      
