- alias: Exterior Front - Dusk
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.virtually_dark
    to: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.front_floods
        - light.rear_floods
      data:
        brightness: 255
    - service: light.turn_on
      entity_id:  
        - light.front_door      
      data:
        brightness: 255
        transition: 300
    - delay:
        seconds: 300
    - service: light.turn_on
      entity_id:  
        - light.front_door      
      data:
        brightness: 255
