- alias: Exterior Front - Dusk
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  action:
    service: light.turn_on
    entity_id:  
      - light.front_door
      - light.front_floods
      - light.rear_floods
    data:
      brightness: 255
      transition: 300      
