- alias: Brighten entryway on unlock
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.front_door
    from: 'on'
    to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 8
    - condition: numeric_state
      entity_id: light.front_door
      value_template: '{{ states.attributes.brightness }}'
      below: 254
  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness: 255
    - delay:
        minutes: 2
    - service: light.turn_on
      entity_id: light.pantry
      data:
        brightness: 100
        transition: 30
