- alias: Morning - Weekend - Stage 3
  hide_entity: True
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: light.turn_off
    entity_id: light.master_bedroom
