- alias: Kitchen Uplighting - Weekends
  hide_entity: true
  trigger:
    - platform: state
      entity_id: light.living_room
    - platform: state
      entity_id: group.family
      to: 'home'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: time
        weekday:
          - sat
          - sun
      - condition: template
        value_template: '{{ now().month == 12 and now().day == 25}}'
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    service: light.turn_on
    entity_id: light.cabinet_lights
    data_template:
      xy_color: >
        {% if now().month == 12 %}
          [0.17,0.7]
        {% else %}
          [0.1605,0.3299]
        {% endif %}
      brightness: >
        {{ states.light.living_room.attributes.brightness }}
