- alias: Kitchen Uplighting - Weekdays
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.brightness_lr
    - platform: state
      entity_id: light.living_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: group.family
      to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action: 
    - service: light.turn_on
      entity_id: light.cabinet_lights
      data_template:
        color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            450
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            450
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}
        brightness: >
          {{ states.light.living_room.attributes.brightness }}
