
################################################################
##               Logitech Harmony Automations                 ##
################################################################

  - alias: Harmony - DirecTV
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Watch DirecTV'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "19594181"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"

  - alias: Harmony - Plex
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Watch Plex'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "19755764"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"

  - alias: Harmony - Netflix
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Watch Netflix'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "19755673"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"

  - alias: Harmony - Hulu
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Watch Hulu'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "20619552"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"

  - alias: Harmony - Prime Video
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Watch Prime Video'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "19752038"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"

  - alias: Harmony - Chromecast
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Watch Chromecast'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "19938341"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"

  - alias: Harmony - Power Off
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      state: 'Power Off'
    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "-1"}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"
          
  - alias: Harmony Light Control - Start
    hide_entity: true
    trigger: 
      - platform: state
        entity_id: sensor.current_activity
        to: 'Watch Plex'
      - platform: state
        entity_id: sensor.current_activity
        to: 'Watch Netflix'
      - platform: state
        entity_id: sensor.current_activity
        to: 'Watch Hulu'
      - platform: state
        entity_id: sensor.current_activity
        to: 'Watch Prime Video'
    condition: 
      - condition: state
        entity_id: group.living_room_lights
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: light.turn_on
      entity_id: group.living_room_lights
      data:
        brightness: 60
        
  - alias: Harmony Light Control - End
    hide_entity: true
    trigger: 
      - platform: state
        entity_id: sensor.current_activity
        from: 'Watch Plex'
      - platform: state
        entity_id: sensor.current_activity
        from: 'Watch Netflix'
      - platform: state
        entity_id: sensor.current_activity
        from: 'Watch Hulu'
      - platform: state
        entity_id: sensor.current_activity
        from: 'Watch Prime Video'
    condition: 
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.current_activity
            state: 'Watch DirecTV'
          - condition: state
            entity_id: sensor.current_activity
            state: 'Watch Chromecast'
          - condition: state
            entity_id: sensor.current_activity
            state: 'PowerOff'
      - condition: state
        entity_id: group.living_room_lights
        state: 'on'
      - condition: state
        entity_id: sensor.floor_lamp
        state: '60'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action: 
      service: light.turn_on
      entity_id: group.living_room_lights
      data:
        brightness: 254
          
        

################################################################
##                    Simulate Presence                       ##
################################################################

  - alias: Simulate Presence 1
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 5
    action:
      service: light.turn_on
      entity_id: group.living_room
      data:
        brightness: 254
        transition: 900

  - alias: Simulate Presence 2
    hide_entity: True
    trigger:
      platform: time
      after: '20:30:00'
    action:
      - service: light.turn_on
        entity_id: group.living_room
        data:
          brightness: 100
      - service: remote.turn_on
        entity_id: remote.living_room
        data: {"activity": "Watch DirecTV"}
#      - service: ifttt.trigger
#        data: {"event": "DirecTV"}

  - alias: Simulate Presence 3
    hide_entity: True
    trigger:
      platform: time
      after: '23:45:00'
    action:
      - service: light.turn_off
        entity_id: group.living_room
      - service: remote.turn_off
        entity_id: remote.living_room 
#      - service: ifttt.trigger
#        data: {"event":"PowerOff"}


  - alias: Simulate Presence 4
    hide_entity: True
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      service: automation.turn_off
      entity_id: group.simulate_presence
