TEST


homeassistant:
  name: Hidden Ridge
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 360
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize

frontend:
updater:
discovery:
#conversation:
recorder:
  purge_days: 7
history:
logbook:
sun:

http: !include ./configuration/http.yaml

automation: !include_dir_merge_list automation

script: !include_dir_merge_named script

remote: !include ./configuration/remote.yaml

input_select: !include ./configuration/input_select.yaml

light: !include ./configuration/light.yaml

nest: !include ./configuration/nest.yaml

climate: !include ./configuration/climate.yaml

cover: !include ./configuration/cover.yaml

ifttt: !include ./configuration/ifttt.yaml

media_player: !include ./configuration/media_player.yaml

device_tracker: !include ./configuration/device_tracker.yaml

mqtt: !include ./configuration/mqtt.yaml

sensor: !include ./configuration/sensor.yaml

switch: !include ./configuration/switch.yaml

group: !include ./configuration/group.yaml
