views:
  - name: Home
    theme: dark-theme
    cards:
      - type: entities
        entities:
          - light.living_room
          - light.master_bedroom
          - light.chandelier
          - light.recessed_lights
      - type: weather-forecast
        entity: weather.yweather
      - type: entity-filter
        filter:
          - entity_id:
            - group.tristans_phone
            - group.crystals_phone
        card: glance
        card_config:
          title: Family
