views:
  - icon: mdi:home
    name: Home
    id: home
    cards:
      - type: vertical-stack
        cards:
        - type: picture-glance
          image: https://smrtho.us/local/resources/images/lovelace/family_edited.jpg
          entities:
            - device_tracker.tristans_phone_wifi
            - device_tracker.crystals_phone_wifi
          filter:
           state: 'home'
          title: "Family"  
        - type: entities
          entities:
            - lock.front_door
            - lock.back_door
            - cover.garage_door_opener
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/master_bedroom_edited.jpg
            entity: light.master_bedroom
            name: "Master Bedroom Lights"
            tap_action: toggle
          - type: entities
            entities: 
              - light.bedroom_floor_lamp
              - light.crystals_nightstand
              - light.tristans_nightstand
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/livingroom_edited.jpg
            entity: light.living_room
            name: "Livingroom Lights"
            tap_action: toggle
          - type: entities
            entities:
              - sensor.current_activity
              - input_select.harmony
              - light.fan
              - climate.downstairs_hallway
              - light.bias_light
              - sensor.protect_down
      - type: vertical-stack
        cards:        
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/kitchen_edited.jpg
            entity: group.kitchen_lighting
            name: "Kitchen Lights"
          - type: entities
            entities:
              - light.overhead_light
              - light.recessed_lights
              - light.chandelier
              - light.pantry
              - light.cabinet_lights
              - sensor.protect_kitchen
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/house_exterior_edited.jpg
            entity: group.exterior
            name: "Exterior Lights"
            tap_action: toggle
          - type: entities
            entities: 
              - light.front_door
              - light.front_floods
              - light.rear_floods
      - type: vertical-stack
        cards:        
          - type: picture-entity
            name: "Office Lights"
            image: https://smrtho.us/local/resources/images/lovelace/office_edited.jpg
            entity: light.desk_lamp
          - type: entities
            entities:
              - climate.upstairs_hallway
              - sensor.protect_up
      - type: entities
        entities:
          - light.foyer     
      - type: entities
        entities:
          - light.dining_room
      - type: weather-forecast
        entity: weather.yweather
      - type: entities
        title: Alarm Zones
        entities:
          - sensor.front_door
          - sensor.back_door
          - sensor.garage_door
          - sensor.front_windows
          - sensor.back_windows
          - sensor.bedroom_windows
  - icon: mdi:cast
    name: Media
    id: media
    cards:
      - type: picture-entity
        image: https://smrtho.us/local/resources/images/lovelace/movie_mode.jpg
        entity: input_boolean.movie_mode
        name: "Movie Mode"
      - type: media-control 
        entity: media_player.all_assistants
      - type: media-control 
        entity: media_player.all_speakers
      - type: media-control 
        entity: media_player.bathroom_assistant
      - type: media-control 
        entity: media_player.bedroom_assistant
      - type: media-control 
        entity: media_player.bedroom_speaker
      - type: media-control 
        entity: media_player.dining_room_speaker
      - type: media-control 
        entity: media_player.garage_speaker
      - type: media-control 
        entity: media_player.house_party_protocol
      - type: media-control 
        entity: media_player.kitchen_assistant
      - type: media-control
        entity: media_player.livingroom_assistant
      - type: media-control 
        entity: media_player.livingroom_directv
      - type: media-control 
        entity: media_player.livingroom_speaker
      - type: media-control 
        entity: media_player.livingroom_tv
      - type: media-control 
        entity: media_player.mancave_directv
      - type: media-control 
        entity: media_player.mancave_tv
      - type: media-control 
        entity: media_player.master_suite
      - type: media-control 
        entity: media_player.party_mode
      - type: media-control 
        entity: media_player.rasplex
  - icon: mdi:video
    name: Camera
    id: camera
    cards:
      - type: picture-entity
        name: Front Door
        entity: camera.downstairs_front_door
        camera_image: camera.downstairs_front_door
      - type: picture-entity
        name: Backyard
        entity: camera.downstairs_yard
        camera_image: camera.downstairs_yard
      - type: picture-entity
        name: Nursery
        entity: camera.upstairs_nursery
        camera_image: camera.upstairs_nursery
  - icon: mdi:settings
    name: Settings
    id: settings
    cards:
      - type: entities
        name: Administration
        entities: 
          - updater.updater
          - input_boolean.disable_away_mode
          - input_boolean.disable_alarm
          - switch.vacation_mode
          - group.simulate_presence
          - input_boolean.disable_all_automations
