views:
  - name: Home
    theme: dark-theme
    cards:
      - type: entities
        entities:
          - light.living_room
          - light.master_bedroom
          - light.chandelier
          - light.recessed_lights
      - type: weather-forecast
        entity: weather.yweather
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/family.jpg
        entities:
          - device_tracker.tristans_phone_wifi
          - device_tracker.crystals_phone_wifi
          - device_tracker.macmini
        title: "Family"
