views:
  - name: Home
    cards:
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/family.jpg
        entities:
          - device_tracker.tristans_phone_wifi
          - device_tracker.crystals_phone_wifi
        filter:
         state: 'home'
        title: "Family"
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/livingroom.jpg
        entity: light.living_room
        title: "Living Room"
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/master_bedroom.jpg
        entity: light.master_bedroom
        title: "Master Bedroom"
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/house_exterior.jpg
        entities:
          - lock.front_door
          - lock.back_door
          - light.front_door
          - light.front_floods
          - light.rear_floods
        filter:
         state: 'home'
        title: "Exterior"        
      - type: weather-forecast
        entity: weather.yweather
      - type: entities
        title: Alarm Zones
        entities:
          - sensor.front_door
          - sensor.back_door
          - sensor.garage_door
          - sensor.front_windows
          - sensor.back_windows
          - sensor.bedroom_windows
      - type: entities
        title: "Garage"
        entities:
          - cover.garage_door_opener
      - type: entities
        title: "Room Lights"
        entities:
          - light.foyer
          - light.dining_room
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/office.jpg
        entity: light.desk_lamp
        title: "Office"
  - name: Media
    cards:
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/movie_mode.jpg
        entity: input_boolean.movie_mode
        title: "Movie Mode"
      - type: media-control
        entity: media_player.livingroom_tv
      - type: media-control
        entity: media_player.livingroom_directv
        
