views:
  - name: Home
    theme: dark-theme
    cards:
      - type: entities
        entities:
          - light.living_room
          - light.master_bedroom
          - light.chandelier
          - light.recessed_lights
      - type: weather-forecast
      - type: entity-filter
        filter:
          - domain: device_tracker
            state: 'home'
        card: glance
        card_config:
          title: People at home
