views:
  - icon: mdi:home
    name: Home
    cards:
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/family_edited.jpg
        entities:
          - device_tracker.tristans_phone_wifi
          - device_tracker.crystals_phone_wifi
        filter:
         state: 'home'
        title: "Family"    
      - type: entities
        entities: 
          - lock.front_door
          - lock.back_door
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/master_bedroom_edited.jpg
        entity: light.master_bedroom
        title: "Master Bedroom"
      - type: entities
        entities: 
          - light.bedroom_floor_lamp
          - light.crystals_nightstand
          - light.tristans_nightstand
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/livingroom_edited.jpg
        entity: light.living_room
        title: "Livingroom Lights"
      - type: entities
        entities:
          - sensor.current_activity
          - input_select.harmony
          - light.fan
          - climate.downstairs_hallway
          - light.bias_light
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/kitchen_edited.jpg
        entity: group.kitchen_lighting
      - type: entities
        entities:
          - light.overhead_light
          - light.recessed_lights
          - light.chandelier
          - light.pantry
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/house_exterior_edited.jpg
        entity: group.exterior
        title: "Exterior Lights"
      - type: entities
        entities: 
          - light.front_door
          - light.flood_lights
      - type: entities
        entities:
          - cover.garage_door_opener 
      - type: entities
        title: Alarm Zones
        entities:
          - sensor.front_door
          - sensor.back_door
          - sensor.garage_door
          - sensor.front_windows
          - sensor.back_windows
          - sensor.bedroom_windows
          - sensor.protect_down
          - sensor.protect_up
          - sensor.protect_kitchen
      - type: entities
        entities:
          - light.dining_room
      - type: entities
        entities:
          - light.foyer
      - type: weather-forecast
        entity: weather.yweather         
  - icon: mdi:cast
    name: Media
    cards:
      - type: entity-picture
        image: https://smrtho.us/local/resources/images/lovelace/movie_mode_edited.jpg
        entity: input_boolean.movie_mode
        title: "Movie Mode"
      - type: media-control
        entity: media_player.livingroom_tv
      - type: media-control
        entity: media_player.livingroom_directv
        
