resources:
  - url: /local/resources/cards/gauge-card.js?v=2
    type: js
  - url: /local/resources/cards/bignumber-card.js?v=1
    type: js

title: Hidden Ridge
views:

#############
# MAIN VIEW #
#############

  - icon: mdi:home
    name: Home
    id: home
    cards:
####   FAMILY STACK

      - type: vertical-stack
        cards:
        - type: picture-glance
          entities:
            - entity: binary_sensor.tristan
              icon: mdi:human-male
              name: "Tristan"
            - entity: binary_sensor.crystal
              icon: mdi:human-female
              name: "Crystal"
          image: /local/resources/images/lovelace/family_edited.jpg
          title: "Family"
          state_image:
            "not_home": /local/resources/images/lovelace/family_away_edited.jpg
            "home": /local/resources/images/lovelace/family_edited.jpg
          entity: group.tristal
        - type: entities
          entities:
            - lock.front_door
            - lock.back_door
            - cover.garage_door_opener
#### LIVINGROOM STACK
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: /local/resources/images/lovelace/livingroom_edited.jpg
            entity: light.living_room
            name: "Livingroom Lights"
            tap_action: toggle
          - type: entities
            entities:
              - sensor.current_activity
              - input_select.harmony
              - light.living_room
              - light.fan
              - climate.downstairs_hallway
              - sensor.protect_down
#### BEDROOM STACK
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: /local/resources/images/lovelace/master_bedroom_edited.jpg
            entity: light.master_bedroom
            name: "Master Bedroom Lights"
            tap_action: toggle
          - type: entities
            entities: 
              - light.bedroom_floor_lamp
              - light.crystals_nightstand
              - light.tristans_nightstand     
#### KITCHEN STACK
      - type: vertical-stack
        cards:        
          - type: picture-entity
            image: /local/resources/images/lovelace/kitchen_edited.jpg
            entity: group.kitchen_lighting
            name: "Kitchen Lights"
          - type: entities
            entities:
              - light.overhead_light
              - light.recessed_lights
              - light.chandelier
              - light.pantry
              - light.cabinet_lights
              - sensor.protect_kitchen
#### EXTERIOR STACK
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: /local/resources/images/lovelace/house_exterior_edited.jpg
            entity: group.exterior
            name: "Exterior Lights"
            tap_action: toggle
          - type: entities
            entities: 
              - entity: light.front_door
                name: Entryway Light
              - light.front_floods
              - light.rear_floods
#### OFFICE STACK
      - type: vertical-stack
        cards:        
          - type: picture-entity
            name: "Office Lights"
            image: /local/resources/images/lovelace/office_edited.jpg
            entity: light.desk_lamp
          - type: entities
            entities:
              - climate.upstairs_hallway
              - sensor.protect_up
      - type: entities
        entities:
          - entity: light.foyer     
            name: Foyer Light
      - type: entities
        entities:
          - entity: light.dining_room
            name: Dining Room Lights
      - type: weather-forecast
        name: Weather
        entity: weather.yweather
      - type: glance
        title: Alarm Zones
        tap_action: toggle
        entities:
          - entity: sensor.front_door
            name: Front
          - entity: sensor.back_door
            name: Back
          - entity: sensor.garage_door
            name: Garage
          - entity: sensor.downstairs_windows
            name: Downstairs
#          - entity: sensor.back_windows
#            name: Back
          - entity: sensor.bedroom_windows
            name: Bedroom
            
##################################
# Filter cards for Media Players #
##################################
            
      - type: entity-filter
        entities:
          - media_player.all_assistants
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.all_assistants
      - type: entity-filter
        entities:
          - media_player.all_speakers
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.all_speakers
      - type: entity-filter
        entities:
          - media_player.bathroom_assistant
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.bathroom_assistant
      - type: entity-filter
        entities:
          - media_player.bedroom_assistant
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.bedroom_assistant
      - type: entity-filter
        entities:
          - media_player.bedroom_speaker
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.bedroom_speaker
      - type: entity-filter
        entities:
          - media_player.dining_room_speaker
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.dining_room_speaker
      - type: entity-filter
        entities:
          - media_player.garage_speaker
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.garage_speaker
      - type: entity-filter
        entities:
          - media_player.house_party_protocol
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.house_party_protocol
      - type: entity-filter
        entities:
          - media_player.livingroom_assistant
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.livingroom_assistant
      - type: entity-filter
        entities:
          - media_player.livingroom_directv
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.livingroom_directv
      - type: entity-filter
        entities:
          - media_player.livingroom_speaker
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.livingroom_speaker
      - type: entity-filter
        entities:
          - media_player.livingroom_tv
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.livingroom_tv
      - type: entity-filter
        entities:
          - media_player.mancave_directv
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.mancave_directv
      - type: entity-filter
        entities:
          - media_player.mancave_tv
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.mancave_tv
      - type: entity-filter
        entities:
          - media_player.master_suite
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.master_suite
      - type: entity-filter
        entities:
          - media_player.party_mode
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.party_mode
      - type: entity-filter
        entities:
          - media_player.rasplex
        state_filter:
          - 'playing'
        show_empty: false
        card: 
          type: media-control
          entity: media_player.rasplex 

          
##########
# LIGHTS #
##########

  - icon: mdi:lightbulb
    name: Lights
    id: lights
    cards:
      - type: entities
        title: Living Room
        entities:
          - light.floor_lamp_left
          - light.floor_lamp_right
          - light.table_lamp
      - type: entities
        title: Master Bedroom
        entities:
          - light.tristans_nightstand
          - light.crystals_nightstand
          - light.bedroom_floor_lamp
      - type: entities
        title: Kitchen
        entities:
          - light.overhead_light
          - light.chandelier
          - light.recessed_lights
          - light.pantry
      - type: entities
        title: Exterior
        entities:
          - light.front_door
          - light.front_floods
          - light.rear_floods
      - type: entities
        title: Foyer
        entities:
          - light.foyer
      - type: entities
        title: Dining Room
        entities:
          - light.dining_room
      - type: entities
        title: Accent Lights
        entities:
          - light.cabinet_lights
          - light.bias_light
          
#################
# MEDIA PLAYERS #
#################

  - icon: mdi:cast
    name: Media
    id: media
    cards:
      - type: picture-entity
        image: /local/resources/images/lovelace/movie_mode.jpg
        entity: input_boolean.movie_mode
        name: "Movie Mode"
      - type: media-control 
        entity: media_player.all_assistants
      - type: media-control 
        entity: media_player.all_speakers
      - type: media-control 
        entity: media_player.bathroom_assistant
      - type: media-control 
        entity: media_player.bedroom_assistant
      - type: media-control 
        entity: media_player.bedroom_speaker
      - type: media-control 
        entity: media_player.dining_room_speaker
      - type: media-control 
        entity: media_player.garage_speaker
      - type: media-control 
        entity: media_player.house_party_protocol
      - type: media-control 
        entity: media_player.kitchen_assistant
      - type: media-control
        entity: media_player.livingroom_assistant
      - type: media-control 
        entity: media_player.livingroom_directv
      - type: media-control 
        entity: media_player.livingroom_speaker
      - type: media-control 
        entity: media_player.livingroom_tv
      - type: media-control 
        entity: media_player.mancave_directv
      - type: media-control 
        entity: media_player.mancave_tv
      - type: media-control 
        entity: media_player.master_suite
      - type: media-control 
        entity: media_player.party_mode
      - type: media-control 
        entity: media_player.rasplex

###########
# CAMERAS #
###########

  - icon: mdi:video
    name: Camera
    id: camera
    cards:
      - type: picture-entity
        name: Front Door
        entity: camera.downstairs_front_door
        camera_image: camera.downstairs_front_door
      - type: picture-entity
        name: Backyard
        entity: camera.downstairs_yard
        camera_image: camera.downstairs_yard
      - type: picture-entity
        name: Nursery
        entity: camera.upstairs_nursery
        camera_image: camera.upstairs_nursery
      - type: map
        aspect_ratio: 74.75%
        entities:
          - entity: device_tracker.google_maps_102616309312724957780
          - entity: device_tracker.google_maps_110746778193138728717
          - zone.home
          - zone.sedgwick
          - zone.ttc
          
#########
# ADMIN #
#########

  - icon: mdi:settings
    name: Settings
    id: settings
    cards:
      - type: vertical-stack
        cards: 
          - type: entities
            title: Administration
            show_header_toggle: false
            entities:
              - input_boolean.disable_away_mode
              - input_boolean.disable_alarm
              - switch.vacation_mode
              - group.simulate_presence
              - input_boolean.disable_all_automations
          - type: iframe
            url: https://embed.windy.com/embed2.html?lat=35.127&lon=-89.843&zoom=7&level=surface&overlay=radar&menu=&message=true&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=35.127&detailLon=-89.843&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1
            aspect_ratio: 100%
#          - type: picture
#            image: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=NQA&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=1&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25525021&lat=0&lon=0&label=you
      - type: vertical-stack
        cards:
          - type: history-graph
            title: 'Titan'
            entities:
              - sensor.cpu_usage
              - sensor.memory_usage
          - type: horizontal-stack
            cards:
              - type: custom:gauge-card
                title: 'CPU'
                entity: sensor.cpu_usage
                min: 0
                max: 100
              - type: custom:gauge-card
                title: 'Memory'
                entity: sensor.memory_usage
                min: 0
                max: 100
          - type: horizontal-stack
            cards:
              - type: custom:gauge-card
                title: 'Plex (Z:)'
                entity: sensor.plex
                min: 0
                max: 100
#                severity:
#                  green: 0
#                  amber: 70
#                  red: 90
              - type: custom:gauge-card
                title: 'Storage (Y:)'
                entity: sensor.storage
                min: 0
                max: 100
#                severity:
#                  green: 0
#                  amber: 70
#                  red: 90
#          - type: horizontal-stack
#            cards:
#              - type: custom:gauge-card
#                title: 'Titan OS'
#                entity: sensor.titan
#                min: 0
#                max: 100
#                severity:
#                  green: 0
#                  amber: 70
#                  red: 90
#              - type: custom:gauge-card
#                title: 'Retina OS'
#                entity: sensor.retina
#                min: 0
#                max: 100 
#                severity:
#                  green: 0
#                  amber: 70
#                  red: 90          
      - type: entities
        title: Critical Devices
        entities: 
          - sensor.huebridge
          - sensor.lightifybridge
          - sensor.harmonyhub
          - sensor.smartthingshub
          - sensor.myq
          - sensor.macmini
          - sensor.rasplex
          - sensor.directv_genie
          - sensor.nesthello
      - type: entities
        title: Cast Devices
        entities: 
          - sensor.google_home_livingroom
          - sensor.google_home_mini_kitchen
          - sensor.google_home_mini_bedroom
          - sensor.google_home_mini_bathroom
          - sensor.chromecast_man_cave
          - sensor.chromecast_audio_dining_room
          - sensor.chromecast_audio_garage
          - sensor.viziocrave360
          - sensor.vizio_m70e3
          - sensor.lg_sj9

#########
# KIOSK #
#########

#  - icon: mdi:tablet
#    name: Kiosk
#    id: kiosk
#    cards:
#      - type: vertical-stack
#        cards: 
#          - type: picture-glance
#            entities:
#              - device_tracker.tristans_phone_wifi
#              - device_tracker.crystals_phone_wifi
#            filter:
#             state: 'home'
#            title: "Family"
#            state_image:
#              "not_home": /local/resources/images/lovelace/family_away_edited.jpg
#              "home": /local/resources/images/lovelace/family_edited.jpg
#            entity: group.tristal 
#          - type: entities
#            entities:
#              - lock.front_door
#              - lock.back_door
#              - cover.garage_door_opener
#      - type: vertical-stack
#        cards: 
#          - type: picture-entity
#            image: /local/resources/images/lovelace/livingroom_edited.jpg
#            entity: group.living_room_lights
#            name: "Living Room Lights"    
#          - type: entities
#            entities:
#              - light.fan
#              - light.bias_light
#              - climate.downstairs_hallway
#      - type: vertical-stack
#        cards:
#          - type: picture-entity
#            image: /local/resources/images/lovelace/master_bedroom_edited.jpg
#            entity: group.master_bedroom
#            name: "Master Bedroom Lights"
#          - type: entities
#            entities:
#              - light.tristans_nightstand
#              - light.crystals_nightstand
#              - light.bedroom_floor_lamp
#      - type: vertical-stack
#        cards: 
#          - type: picture-entity
#            image: /local/resources/images/lovelace/kitchen_edited.jpg
#            entity: group.kitchen_lighting
#            name: "Kitchen Lights"     
#          - type: entities
#            entities: 
#              - light.overhead_light
#              - light.recessed_lights
#              - light.chandelier
