views:
  - icon: mdi:home
    name: Home
    cards:
      - type: vertical-stack
        cards:
        - type: picture-glance
          image: https://smrtho.us/local/resources/images/lovelace/family_edited.jpg
          entities:
            - device_tracker.tristans_phone_wifi
            - device_tracker.crystals_phone_wifi
          filter:
           state: 'home'
          title: "Family"  
        - type: horizontal-stack
          cards:
            - type: picture-entity
              name: " "
              image: https://smrtho.us/local/resources/images/lovelace/front_door_edited.jpg
              entity: lock.front_door
              tap_action: toggle
            - type: picture-entity
              name: " "
              image: https://smrtho.us/local/resources/images/lovelace/back_door_edited.jpg
              entity: lock.back_door
              tap_action: toggle
            - type: picture-entity
              name: " "
              image: https://smrtho.us/local/resources/images/lovelace/garage.jpg
              entity: cover.garage_door_opener
              tap_action: toggle
        - type: entities
          entities:
            - cover.garage_door_opener    
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/master_bedroom_edited.jpg
            entity: light.master_bedroom
            title: "Master Bedroom"
            tap_action: toggle
          - type: entities
            entities: 
              - light.bedroom_floor_lamp
              - light.crystals_nightstand
              - light.tristans_nightstand
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/livingroom_edited.jpg
            entity: light.living_room
            title: "Livingroom"
            tap_action: toggle
          - type: entities
            entities:
              - sensor.current_activity
              - input_select.harmony
              - light.fan
              - climate.downstairs_hallway
              - light.bias_light
      - type: vertical-stack
        cards:        
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/kitchen_edited.jpg
            entity: group.kitchen_lighting
            tap_action: toggle
          - type: entities
            entities:
              - light.overhead_light
              - light.recessed_lights
              - light.chandelier
              - light.pantry
      - type: vertical-stack
        cards:
          - type: picture-entity
            image: https://smrtho.us/local/resources/images/lovelace/house_exterior_edited.jpg
            entity: group.exterior
            title: "Exterior Lights"
            tap_action: toggle
          - type: entities
            entities: 
              - light.front_door
              - light.front_floods
              - light.rear_floods
      - type: entities
        entities:
          - light.foyer     
      - type: entities
        entities:
          - light.dining_room
      - type: weather-forecast
        entity: weather.yweather
      - type: entities
        title: Alarm Zones
        entities:
          - sensor.front_door
          - sensor.back_door
          - sensor.garage_door
          - sensor.front_windows
          - sensor.back_windows
          - sensor.bedroom_windows
          - sensor.protect_down
          - sensor.protect_up
          - sensor.protect_kitchen
  - icon: mdi:cast
    name: Media
    cards:
      - type: picture-entity
        image: https://smrtho.us/local/resources/images/lovelace/movie_mode_edited.jpg
        entity: input_boolean.movie_mode
        title: "Movie Mode"
      - type: media-control
        entity: media_player.livingroom_tv
      - type: media-control
        entity: media_player.livingroom_directv
        
