views:
  - name: Home
    theme: dark-theme
    cards:
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/family.jpg
        entities:
          - device_tracker.tristans_phone_wifi
          - device_tracker.crystals_phone_wifi
        filter:
         state: 'home'
        title: "Family"
      - type: entities
        entities:
          - lock.front_door
          - lock.back_door
        title: "Locks"
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/livingroom.jpg
        entities:
          - light.floor_lamp_left
          - light.floor_lamp_right
          - light.table_lamp
          - light.fan
        filter:
         state: 'home'
        title: "Living Room"
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/bedroom.jpg
        entities:
          - light.tristans_nightstand
          - light.crystals_nightstand
          - light.bedroom_floor_lamp
        filter:
         state: 'home'
        title: "Master Bedroom"
      - type: entities
        entities:
          - light.living_room
          - light.master_bedroom
          - light.chandelier
          - light.recessed_lights
      - type: picture-glance
        image: https://smrtho.us/local/resources/images/lovelace/home-exterior.jpg
        entities:
          - light.front_door
          - light.front_floods
          - light.rear_floods
        filter:
         state: 'home'
        title: "Exterior"
      - type: entities
        entities:
          - light.living_room
          - light.master_bedroom
          - light.chandelier
          - light.recessed_lights          
      - type: weather-forecast
        entity: weather.yweather
        title: 'Weather'

