- alias: Rain - Exterior Lights - Start
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.virtually_dark
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.front_door
      data: 
        brightness: 254
        transition: 60
    - service: light.turn_on
      entity_id: light.flood_lights
      data:
        brightness: 254
