- alias: Rain Exterior Lights Start
  trigger:
    - platform: state
      entity_id: binary_sensor.rain
      to: 'on'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 8
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 8
    - condition: state
      entity_id: binary_sensor.rain
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.frontdoor
      data: 
        brightness: 254
        transition: 60
    - service: light.turn_on
      entity_id: light.flood_lights
      data:
        brightness: 254
