- alias: Rain - Occupied
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_icon
      to: 'rain'
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: state
      entity_id: sensor.dark_sky_icon
      state: 'rain'
  action:
    service: light.turn_on
    entity_id: light.living_room
    data:
      brightness: 254
      transition: 60
    data_template:
      color_temp: >
        {% if (states.sensor.time.state | round(2)) <= 09.50 %}
          250
        {% else %}
          366
        {% endif %}
