- alias: Rain - Occupied - Start
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.rain
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: state
      entity_id: binary_sensor.rain
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.front_door
      data: 
        brightness: 254
        transition: 60
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 254
        transition: 60
      data_template:
        color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 5 %}
            366
          {% elif (states.sensor.time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}
