- alias: Rain Unoccupied Start
  trigger:
    - platform: state
      entity_id: binary_sensor.rain
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: state
      entity_id: binary_sensor.rain
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 150
        transition: 60
      data_template:
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}  
