- alias: Rain - Unoccupied - Stop
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.virtually_dark
      to: 'off'
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: 
        - light.living_room
      data:
        transition: 60
