- alias: Rain - Unoccupied - Start
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.virtually_dark
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 150
        transition: 300
      data_template:
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}  
