- alias: Bias Light - On
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.current_activity
      from: 'PowerOff'
  condition:
    - condition: state
      entity_id: light.bias_light
      state: 'off'
  action: 
    - service: light.turn_on
      entity_id: light.bias_light
      data_template:
        color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            450
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.time.state | round(2)) < 22.25 %}
            300
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            500
          {% else %}
          {% endif %}
        brightness: 1
    - service: light.turn_on
      entity_id: light.bias_light
      data_template:
        brightness: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            255
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            175
          {% elif (states.sensor.time.state | round(2)) < 22.25 %}
            175
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            255
          {% else %}
          {% endif %}
        transition: 10
        
- alias: Bias Light - Off
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.current_activity
      to: 'PowerOff'
  condition:
    - condition: state
      entity_id: light.bias_light
      state: 'on'
  action: 
    - service: light.turn_on
      entity_id: light.bias_light
      data:
        brightness: 1
        transition: 10
    - service: light.turn_off
      entity_id: light.bias_light

- alias: Bias Light - Fade
  hide_entity: True
  trigger:
    platform: time
    at: '9:30:00'
  condition:
    - condition: state
      entity_id: light.bias_light
      state: 'on'
    - condition: template
      value_template: '{{ states.light.bias_light.attributes.color_temp == 200 }}'
  action:
    - service: light.turn_on  
      entity_id: light.bias_light
      data:
        color_temp: 300
        brightness: 254
        transition: 1800
