- alias: Foyer Lights - Doorbell pushed
  hide_entity: True
  trigger: 
    platform: state
    entity_id: binary_sensor.ring_doorbell
    to: 'on'
  action: 
    - service: script.turn_off
      entity_id: script.foyer_lights_off
    - service: light.turn_on
      entity_id: light.foyer
      data: 
        brightness: 254
    - service: script.turn_on
      entity_id: script.foyer_lights_off
