- alias: Sunrise - Unoccupied
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5
  condition: 
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.living_room
    - service: light.turn_off
      entity_id: light.pantry
