- alias: Sunset - Unoccupied
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 12
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    service: light.turn_on
    entity_id: light.living_room
    data:
      color_temp: 300
      brightness: 150
      transition: 600
