- alias: Bedtime - Bedroom Lights
  hide_entity: True
  trigger:
    platform: time
    after: '22:30:00'
  condition:
    condition: state
    entity_id: group.tristal
    state: 'home'
  action:
    service: light.turn_on
    entity_id: light.master_bedroom
    data:
      brightness: 150
      color_temp: 500
      transition: 60
