- alias: Bedtime - Livingroom Lights
  hide_entity: True
  trigger:
    platform: time
    after: '22:30:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
  action: 
    service: light.turn_on
    entity_id: group.living_room_lights
    data: 
      color_temp: 500
      transition: 3600
