- alias: Bedtime - Livingroom Lights
  hide_entity: True
  trigger:
    platform: time
    after: '21:30:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action: 
    - service: light.turn_on
      entity_id:
        - light.floor_lamp_left
        - light.floor_lamp_right
        - light.table_lamp
        - light.living_room
      data: 
        color_temp: 500
        transition: 3600
    - condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - delay:
            seconds: 15
        - condition: state
          entity_id: group.family
          state: 'home'
        - condition: state
          entity_id: light.cabinet_lights
          state: 'on' 
    - service: light.turn_on
      entity_id: light.cabinet_lights
      data: 
        color_temp: 450
        transition: 3600
