- alias: disable all automations
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.disable_all_automations
  action:
    - service_template: >
        {% if states.input_boolean.disable_all_automations.state == 'on' %}
          input_boolean.turn_on
        {% elif states.input_boolean.disable_all_automations.state == 'off' %}
          input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.disable_alarm
    - service_template: >
        {% if states.input_boolean.disable_all_automations.state == 'on' %}
          switch.turn_on
        {% if states.input_boolean.disable_all_automations.state == 'off' %}
          switch.turn_off
        {% endif %}
      entity_id: switch.vacation_mode
      
