- alias: Evening - Lights
  hide_entity: True
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: template
      value_template: '{{ states.light.table_lamp.state != "off" }}'
  action:
    - service: script.evening_lights_bedroom
    - service: script.evening_lights_livingroom
    - condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: light.cabinet_lights
          state: 'on' 
    - delay:
        seconds: 15
    - service: light.turn_on
      entity_id: light.cabinet_lights
      data: 
        color_temp: 366
        transition: 300
