- alias: Bedroom Remote
  trigger:
    platform: state
    entity_id: input_select.bedroom_tv
    from: 'Select Input'
  action:
    - service_template: >
          {% if states.input_select.bedroom_tv.state == "YouTubeTV" %}
            script.bedroom_tv_youtubetv
          {% elif states.input_select.bedroom_tv.state == "YouTube" %}
            script.bedroom_tv_youtube
          {% elif states.input_select.bedroom_tv.state == "Netflix" %}
            script.bedroom_tv_netflix
          {% elif states.input_select.bedroom_tv.state == "Hulu" %}
            script.bedroom_tv_hulu
          {% elif states.input_select.bedroom_tv.state == "Disney+" %}
            script.bedroom_tv_disneyplus
          {% elif states.input_select.bedroom_tv.state == "Plex" %}
            script.bedroom_tv_plex
          {% elif states.input_select.bedroom_tv.state == "Prime Video" %}
            script.bedroom_tv_primevideo
          {% elif states.input_select.bedroom_tv.state == "Power Off" %}
            script.bedroom_tv_poweroff
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.bedroom_tv
      data_template:
        option: "Select Input"

- alias: Bedroom Cast Control Start
  trigger: 
    - platform: state
      entity_id: media_player.mi_box_s
      to: 'playing'
  condition:
    condition: template
    value_template: "{{ states.media_player.vizio_smartcast_2.state != 'off'}}"
  action: 
    - service: media_player.turn_on
      entity_id: media_player.vizio_smartcast_2
