- alias: Bedoom Remote
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.bedroom_tv
    from: 'Select Input'
  action:
    - service_template: >
          {% if is_state("input_select.bedroom_tv", "Watch DirecTV") %}
            script.bedroom_tv_directv
          {% elif is_state("input_select.bedroom_tv", "Watch Smartcast") %}
            script.bedroom_tv_smartcast
          {$ elif is_state("input_select.bedroom_tv", "Play Switch") %}
            script.bedroom_tv_switch
          {$ elif is_state("input_select.bedroom_tv", "Power Off") %}
            script.bedroom_tv_poweroff
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.bedroom_tv
      data_template:
        option: "Select Input"
