- alias: Bedroom Remote
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.bedroom_tv
    from: 'Select Input'
  action:
    - service_template: >
          {% if states.input_select.bedroom_tv.state == "Watch Smartcast" %}
            script.bedroom_tv_smartcast
          {% elif states.input_select.bedroom_tv.state == "Play Switch" %}
            script.bedroom_tv_switch
          {% elif states.input_select.bedroom_tv.state == "Power Off" %}
            script.bedroom_tv_poweroff
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.bedroom_tv
      data_template:
        option: "Select Input"
