- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.livingroom
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Watch DirecTV") %}
            19594181
          {% elif is_state("input_select.harmony", "Watch Plex") %}
            28102020
          {% elif is_state("input_select.harmony", "Watch Netflix") %}
            28121828
          {% elif is_state("input_select.harmony", "Watch Smartcast") %}
            28101990
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.livingroom
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Light Control - Start
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: input_boolean.harmony_lighting_control
      from: 'off'
      to: 'on'
#    - platform: state
#      entity_id: sensor.current_activity
#      to: 'Watch Plex'
    - platform: state
      entity_id: sensor.rasplex_status
      to: 'playing'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Watch Netflix'
  condition:
    - condition: state
      entity_id: input_boolean.harmony_lighting_control
      state: 'on'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 12
    - condition: state
      entity_id: input_boolean.movie_mode
      state: 'off'
  action:
    - service: input_number.set_value
      entity_id: input_number.harmony_dim
      data_template:
        value: '{{states.light.living_room.attributes.brightness | int}}'
    - service: light.turn_on
      entity_id: light.living_room
      data_template:
        brightness: >
          {% if states.input_number.harmony_dim.state|int >=60 %}
            60
          {% else %}
            {{ states.input_number.harmony_dim.state }}
          {% endif %}
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}
    - service: light.turn_on
      entity_id: light.bias_light
      data_template:
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}
      
- alias: Harmony Light Control - End
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Plex'
    - platform: state
      entity_id: sensor.rasplex_status
      to: 'paused'    
    - platform: state
      entity_id: sensor.rasplex_status
      to: 'stopped'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Netflix'
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch Plex'
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch DirecTV'
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch Smartcast'
        - condition: state
          entity_id: sensor.current_activity
          state: 'PowerOff'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 12
    - condition: state
      entity_id: input_boolean.movie_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.goodnight_initiated
      state: 'off'
  action: 
    service: light.turn_on
    entity_id: light.living_room
    data_template:
      transition: > 
        {% if states.sensor.rasplex_status.state == 'stopped' %}
          5
        {% else %}
          1
        {% endif %}
      brightness:
        '{{states.input_number.harmony_dim.state | int }}'
      color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}

- alias: Harmony Lighting Control Off
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: input_boolean.harmony_lighting_control
      from: 'on'
      to: 'off'
  action: 
    service: light.turn_on
    entity_id: light.living_room
    data_template:
      brightness: 
        '{{ states.input_number.harmony_dim.state | int }}'
    

- alias: Set Saved Brightness
  hide_entity: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: light.turn_on
      entity_id: 
        - light.saved_brightness
        - light.movie_mode
      data:
        brightness: 254

- alias: Harmony Cast Control - Start
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: media_player.livingroom_tv
      to: 'playing'
  action: 
    - service: remote.turn_on
      entity_id: remote.livingroom
      data:
        activity: 28122446

- alias: Movie Mode - Start
  hide_entity: true
  trigger: 
    platform: state
    entity_id: input_boolean.movie_mode
    from: "off"
    to: "on"
  action: 
    - service: input_number.select_value
      entity_id: input_number.movie_mode
      data_template:
        value: '{{states.light.living_room.attributes.brightness | int}}'
    - service: light.turn_off
      entity_id:
        - light.table_lamp
        - light.cabinet_lights
        - light.recessed_lights
        - light.overhead_light
        - light.chandelier
        - light.pantry
      data:
        transition: 15
    - service: light.turn_on
      entity_id:
        - light.floor_lamp_left
        - light.floor_lamp_right
      data:
        brightness: 60
        color_temp: 500
        transition: 15
    - service: light.turn_on
      entity_id: light.bias_light
      data:
        color_temp: 500
        transition: 15
        brightness: 175
        
- alias: Movie Mode - Stop
  hide_entity: true
  trigger: 
    platform: state
    entity_id: input_boolean.movie_mode
    from: "on"
    to: "off"
  action:
    - service: light.turn_on
      data:
        transition: 15
      data_template:
        entity_id: >
          {% if states.input_number.movie_mode.state | int == (states.light.floor_lamp_left.attributes.brightness | int + states.light.floor_lamp_right.attributes.brightness | int) /2%}
            light.table_lamp
          {% else %}
            light.living_room
          {% endif %}
        brightness:
          '{{ states.input_number.movie_mode.state | int }}'
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}
    - service: light.turn_on
      entity_id: 
        - light.pantry
        - light.cabinet_lights
      data:
        transition: 15
    - service: light.turn_on
      entity_id: light.bias_light
      data:
        transition: 15
        brightness: 175
      data_template:
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}
