- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Watch DirecTV") %}
            19594181
          {% elif is_state("input_select.harmony", "Watch Plex") %}
            28102020
          {% elif is_state("input_select.harmony", "Watch Netflix") %}
            28121828
          {% elif is_state("input_select.harmony", "Watch Smartcast") %}
            28101990
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Light Control - Start
  hide_entity: true
  trigger: 
#    - platform: state
#      entity_id: sensor.current_activity
#      to: 'Watch Plex'
    - platform: state
      entity_id: media_player.rasplex
      to: 'playing'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Watch Netflix'
  condition: 
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 12
  action:
    - service: input_slider.select_value
      entity_id: input_slider.harmony_dim
      data_template:
        value: '{{states.light.living_room.attributes.brightness | int}}'
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 60
      data_template:
        color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}
    - service: light.turn_on
      entity_id: light.bias_light
      data_template:
        color_temp: >
          % if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}
      
- alias: Harmony Light Control - End
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Plex'
    - platform: state
      entity_id: media_player.rasplex
      to: 'paused'
    - platform: state
      entity_id: media_player.rasplex
      to: 'idle'     
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Netflix'
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch Plex'
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch DirecTV'
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch Smartcast'
        - condition: state
          entity_id: sensor.current_activity
          state: 'PowerOff'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 12
  action: 
    service: light.turn_on
    entity_id: light.living_room
    data_template:
      brightness:
        '{{states.input_slider.harmony_dim.state | int }}'
      color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}

- alias: Set Saved Brightness
  hide_entity: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: light.turn_on
      entity_id: 
        - light.saved_brightness
        - light.movie_mode
      data:
        brightness: 254

- alias: Harmony Cast Control - Start
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: media_player.livingroom
      to: 'playing'
  action: 
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: 28122446
