- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "DirecTV") %}
            19594181
          {% elif is_state("input_select.harmony", "Plex") %}
            19755764
          {% elif is_state("input_select.harmony", "Netflix") %}
            23422788
          {% elif is_state("input_select.harmony", "Hulu") %}
            20619552
          {% elif is_state("input_select.harmony", "Prime Video") %}
            19752038
          {% elif is_state("input_select.harmony", "Chromecast") %}
            19938341
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Light Control - Start
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: sensor.current_activity
      to: 'Plex'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Netflix'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Hulu'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Prime Video'
  condition: 
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.living_room
    data:
      brightness: 60
    data_template:
      color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            250
          {% elif (states.sensor.time.state | round(2)) <= 22.49 %}
            366
          {% elif (states.sensor.time.state | round(2)) >= 22.50 %}
            500
          {% else %}
          {% endif %}
      
- alias: Harmony Light Control - End
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: sensor.current_activity
      from: 'Plex'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Netflix'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Hulu'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Prime Video'
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.current_activity
          state: 'DirecTV'
        - condition: state
          entity_id: sensor.current_activity
          state: 'Chromecast'
        - condition: state
          entity_id: sensor.current_activity
          state: 'PowerOff'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action: 
    service: light.turn_on
    entity_id: light.living_room
    data:
      brightness: 254
    data_template:
      color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            250
          {% elif (states.sensor.time.state | round(2)) <= 22.49 %}
            366
          {% elif (states.sensor.time.state | round(2)) >= 22.50 %}
            500
          {% else %}
          {% endif %}
