- alias: Harmony - DirecTV
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data template:
        activity:
          {% if is_state("input_select.harmony", "Watch DirecTV") %}
            19594181
          {% elif is_state("input_select.harmony", "Watch Plex") %}
            19755764
          {% elif is_state("input_select.harmony", "Watch Netflix") %}
            19755673
          {% elif is_state("input_select.harmony", "Watch Hulu") %}
            20619552
          {% elif is_state("input_select.harmony", "Watch Prime Video") %}
            19752038
          {% elif is_state("input_select.harmony", "Watch Chromecast") %}
            19938341
          {% elif is_state("input_select.harmony", "Watch Power OFf") %}
            -1
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

- alias: Harmony Light Control - Start
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: sensor.current_activity
      to: 'Watch Plex'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Watch Netflix'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Watch Hulu'
    - platform: state
      entity_id: sensor.current_activity
      to: 'Watch Prime Video'
  condition: 
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: group.living_room_lights
    data:
      brightness: 60
      
- alias: Harmony Light Control - End
  hide_entity: true
  trigger: 
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Plex'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Netflix'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Hulu'
    - platform: state
      entity_id: sensor.current_activity
      from: 'Watch Prime Video'
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch DirecTV'
        - condition: state
          entity_id: sensor.current_activity
          state: 'Watch Chromecast'
        - condition: state
          entity_id: sensor.current_activity
          state: 'PowerOff'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
    - condition: state
      entity_id: sensor.floor_lamp
      state: '60'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action: 
    service: light.turn_on
    entity_id: group.living_room_lights
    data:
      brightness: 254
