- alias: alarm triggered
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door
        - binary_sensor.back_windows
        - binary_sensor.bedroom_windows
        - binary_sensor.front_door
        - binary_sensor.garage_door
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.garage_hot_start
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_alarm
      state: 'off'
  action:
    service: notify.all_devices
    data:
      data:
        group: alarm
        title: "Home Assistant Alert"
        clickAction: "https://smrtho.us"
        icon_url: "https://github.com/home-assistant/home-assistant-assets/blob/master/logo-round-192x192.png?raw=true"
        importance: high
#        actions:
#          - action: open
#            icon: "/local/resources/images/notifications/chrome.png"
#            title: Open Home Assistant
#          - action: activate_siren
#            icon: "/local/resources/images/notifications/alarm.png"
#            title: Activate Siren  
    data_template:
      message: >
        {% if  states.binary_sensor.back_door.state == 'on' %}
          "The back door has just opened unexpectedly."
        {% elif states.binary_sensor.front_windows.state == 'on' %}
          "A front window has just opened unexpectedly."
        {% elif states.binary_sensor.bedroom_windows.state == 'on' %}
          "A bedroom window has just opened unexpectedly."
        {% elif states.binary_sensor.back_windows.state == 'on' %}
          "A back window has just opened unexpectedly."
        {% elif states.binary_sensor.front_door.state == 'on' %}
          "The front door has just opened unexpectedly."
        {% elif states.binary_sensor.garage_door.state == 'on' %}
          "The garage door has just opened unexpectedly."
        {% else %}
          "An unexpected error has occurred with an alarm sensor."
        {% endif %}
