- alias: Alarm triggered
  hide_entity: True
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.back_door
        - binary_sensor.back_windows
        - binary_sensor.bedroom_windows
        - binary_sensor.front_door
        - binary_sensor.garage_door
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.garage_hot_start
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_alarm
      state: 'off'
  action:
    service: notify.chrome_notifications
    data:
      data:
        target:
          - Tristans Phone
          - Tristans Work Laptop
          - Crystals Phone
        title: "Home Assistant Alert"
        url: "https://smrtho.us"
        actions:
          - action: open
            icon: "/local/resources/images/notifications/chrome.png"
            title: Open Home Assistant
          - action: activate_siren
            icon: "/local/resources/images/notifications/alarm.png"
            title: Activate Siren  
    data_template:
      message: >
        {% if  states.binary_sensor.back_door.state == 'on' %}
          The back door has just opened unexpectedly.
        {% elif states.binary_sensor.front_windows.state == 'on' %}
          A front window has just opened unexpectedly.
        {% elif states.binary_sensor.bedroom_windows.state == 'on' %}
          A bedroom window has just opened unexpectedly.
        {% elif states.binary_sensor.back_windows.state == 'on' %}
          A back window has just opened unexpectedly.
        {% elif states.binary_sensor.front_door.state == 'on' %}
          The front door has just opened unexpectedly.
        {% elif states.binary_sensor.garage_door.state == 'on' %}
          The garage door has just opened unexpectedly.
        {% else %}
          Error.
        {% endif %}d
