- alias: Doorbell Battery Low
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.doorbell_battery
      below: 15
  action:
    service: notify.messenger_notifications
    data:
      target:
        - !secret tristans_phone_number
      message: "The Ring doorbell's battery is critically low. Please recharge it."
        
