- alias: Doorbell Battery Low
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.doorbell_battery
      below: 15
  action:
    service: notify.hidden_ridge
    data:
      target:
        - !secret tristans_phone_number
        - !secret crystals_phone_number
    data:
      message: "The Ring doorbell's battery is critically low. Please recharge it."
        
