- alias: Doorbell Battery Low
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.doorbell_battery
      below: 15
  action:
    service: notify.chrome_notifications
    data:
      data:
        target: Tristans Phone
        title: "Home Assistant Alert"
        message: "The Ring doorbell's battery is critically low. Please recharge it."
        url: "https://smrtho.us/states/group.settings"
