- alias: Garage door open
  hide_entity: True
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    state: 'open'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    service: tts.google_say
    entity_id:
      - media_player.downstairs
      - media_player.google_home_2
    data: 
      message: 'Heads up, the garage is currently open.'

- alias: Garage Notify
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener
      from: 'closed'
      to: 'open'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.foyer
      data:
        brightness: 255
        flash: short
    - delay:
      seconds: 1
    - service: light.turn_on
      entity_id: light.foyer
      data:
        brightness: 255
        flash: short
