- alias: Garage door open Home
  hide_entity: True
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    to: 'open'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.all_assistants
      data: 
        volume_level: 0.5
#    - service: tts.google_say
#      entity_id: media_player.all_assistants
    - service: notify.google_assistant
      data: 
        message: 'Heads up, the garage is currently open.'
 
- alias: Garage door open Away
  hide_entity: True
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    to: 'open'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    service: notify.chrome_notifications
    data:
      data:
        title: "Home Assistant Alert"
        url: "https://smrtho.us"
        message: "The Garage Door is open."
        target:
          - Tristans Phone
          - Crystals Phone
        actions:
        - action: open
          icon: "/local/resources/images/notifications/chrome.png"
          title: Open Home Assistant
        - action: close_garage
          icon: "/local/resources/images/notifications/garage.png"
          title: Close Garage Door  


- alias: 'Close Garage Event'
  hide_entity: true
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: close_garage
  action:
    - service: cover.close
      entity_id: cover.garage_door_opener
    - delay: 
        minutes: 1
    - service: notify.chrome_notifications
      data:
        data:
          title: "Home Assistant Alert"
          url: "https://smrtho.us"
          target:
            - Tristans Phone
            - Crystals Phone
      data_template:
        message: >
          {% if  states.cover.garage_door_opener.state == 'closed' %}
            The garage is now closed.
          {% elif states.cover.garage_door_opener.state == 'open' %}
            An error occurred closing the garage. 
          {% else %}
            An error occurred closing the garage. 
          {% endif %}
    
- alias: Garage Notify
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener
      to: 'open'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.foyer
      data:
        brightness: 255
        flash: short
    - delay:
        seconds: 5
    - service: light.turn_on
      entity_id: light.foyer
      data:
        brightness: 255
        flash: short
