- alias: Garbage reminder
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
    for:
      minutes: 30
  condition: 
    - condition: time
      weekday: mon
  action:
    entity_id: media_player.downstairs
    data: 
      message: 'Heads up, tomorrow is trash day.'
