- alias: Garbage reminder
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
    for:
      minutes: 30
  condition: 
    - condition: time
      weekday: mon
  action:
    - service: media_player.volume_set
      entity_id: 
        - media_player.google_home
        - media_player.downstairs
      data: 
        volume_level: 0.5
    - service: tts.google_say
      entity_id: 
        - media_player.downstairs
        - media_player.google_home_2
      data: 
        message: 'Heads up, tomorrow is trash day.'
