- alias: Garbage reminder
  hide_entity: true
  trigger:
    platform: state
    entity_id:
      - device_tracker.tristans_phone
      - device_tracker.crystals_phone
    to: 'home'
    for:
      minutes: 30
  condition: 
    - condition: time
      weekday: mon
  action:
    service: tts.google_say
    entity_id: media_player.downstairs
    data: 
      message: 'Heads up, tomorrow is trash day.'
