- alias: Garbage reminder
  hide_entity: true
  trigger:
    platform: state
    entity_id: 
      - group.tristans_phone
      - group.crystals_phone
      - device_tracker.matts_phone
      - device_tracker.taylors_phone
      - device_tracker.donnas_phone
    to: 'home'
    for:
      minutes: 30
  condition: 
    - condition: time
      weekday: mon
  action:
    - service: media_player.volume_set
      entity_id: media_player.all_assistants
      data: 
        volume_level: 0.5
#    - service: tts.google_say
#      entity_id: media_player.all_assistants
    - service: notify.google_assistant
      data: 
        message: 'Heads up, tomorrow is trash day.'
