- alias: IP address changed
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.myipopendnscom
  action:
    service: notify.messenger_notifications
    data:
      target:
        - !secret tristans_phone_number
      message: "Your IP address has changed. Please update DNS records."
