- alias: IP address changed
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.myipopendnscom
  action:
    service: notify.hidden_ridge
    data:
      target:
        - !secret tristans_phone_number
      data_template:
        message: "Your IP address has changed to {{states.sensor.myipopendnscom.state}}. Please update dreamhost DNS records."
