- alias: Severe Weather
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.pws_alerts
    above: 0
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.party_mode
      data_template: 
        message: >
          The National Weather Service in Memphis Tennessee has issued a {{states.sensor.pws_alerts.attributes.Description}} in your area. Please take necessary precautions.
    - service: media_player.volume_set
      entity_id: 
        - media_player.party_mode
      data: 
        volume_level: 0.5
