- alias: Severe Weather
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.pws_alerts
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: template  
      value_template: '{{states.sensor.pws_alerts.state != 0}}'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.party_mode
      data_template: 
        message: >
          Heads up. The National Weather Service has issued a {{states.sensor.pws_alerts.attributes.Description}} for this area.
    - service: media_player.volume_set
      entity_id: 
        - media_player.party_mode
      data: 
        volume_level: 0.5
