- alias: 'Activate Siren'
  hide_entity: true
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: activate_siren
  action:
    - service: media_player.play_media
      entity_id: media_player.all_speakers
      data:
        media_content_type: "audio/mp3" 
        media_content_id: "http://smrtho.us/storage/siren.mp3"
    - service: media_player.set_volume
      entity_id: media_player.all_speakers
      data: 
        volume_level: 1.0
