- alias: System temp too high
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperature
    above: 175
  action:
    service: notify.hidden_ridge
    data:
      target:
        - !secret tristans_phone_number
      message: "System temperature has exceeded 175°."

          
- alias: System CPU too high
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_used
    above: 50
    for:
      minutes: 10
  action:
    service: notify.hidden_ridge
    data:
      target:
        - !secret tristans_phone_number
      message: "System CPU usage has exceeded 50% for an extended period."
          
          
- alias: 'Restart System Event'
  hide_entity: true
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: restart_system
  action:
    - service: shell_command.reboot_now
    
  
