- alias: 'update available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.mobile_app_tristan_s_note_20_ultra
    data:
      message: "An update to Home Assistant is available."
      title: "Home Assistant Alert"
      clickAction: "https://home-assistant.io/blog"
      group: update
