- alias: 'update available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.hidden_ridge
    data:
      target:
        - !secret tristans_phone_number
        - !secret crystals_phone_number
      message: "Home Assistant update available."
