- alias: 'update available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.chrome_notifications
    data:
      target: Tristans Phone 
      message: "Home Assistant update available."
