- alias: Update Available
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.hass_update_available
    from: 'No'
  action: 
    - service: group.set_visibility
      entity_id: group.update_available
      data:
        visible: true
    - service: notify.hidden_ridge
      data:
        target:
        - !secret tristans_phone_number
    data_template:
      message: >
        Version {{states.sensor.hass_update_available.state}} is now available. 
    
- alias: No Update Available
  hide_entity: True
  trigger:
    - platform: event
      event_type: homeassistant_start
    - platform: state
      entity_id: sensor.hass_update_available
      to: 'No'
  action: 
    service: group.set_visibility
    entity_id: group.update_available
    data:
      visible: false
