- alias: 'update available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.chrome_notifications
    data:
      data:
        target: Tristans Phone 
        title: "Home Assistant Alert"
        url: "https://home-assistant.io/blog/"
        message: "Home Assistant update available."
