- alias: Christmas Lights ON
  hide_entity: True
  trigger: 
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  condition:
    condition: template
    value_template: '{{ now().month == 12 }}'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_lights
     
- alias: Christmas Lights OFF
  hide_entity: True
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: state
      entity_id: input_boolean.goodnight_initiated
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.christmas_lights


- id: christmas_light_panel_visiblity
  alias: 'Christmas Light Panel Visiblity'
  hide_entity: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: group.set_visibility
      entity_id: group.christmas
      data_template:
        visible: >
          {% if now().month >= 11 %}true{%else%}false{%endif%}
