- alias: Christmas Lights ON
  hide_entity: True
  trigger: 
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  condition:
    condition: template
    value_template: '{{ now().month == 12 }}'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_lights
     
- alias: Christmas Lights OFF
  hide_entity: True
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: state
      entity_id: input_boolean.goodnight_initiated
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.christmas_lights


- id: christmas_light_panel_visiblity
  alias: 'Christmas Light Panel Visiblity'
  hide_entity: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '00:00:00'
  action:
    service_template: >
      {% if now().month == 12 %}
        input_boolean.turn_on
      {% elif now().month != 12 %}
        input_boolean.turn_off
      {% endif %}
    entity_id: input_boolean.christmas_lights

- alias: Red-Green Spin
  hide_entity: True
  initial_state: false
  trigger:
    platform: time
    seconds: /6
  action: 
    - service: light.turn_on
     entity: light.dining_room_left
     data:
       brightness: 255
       rgb_color: 0,255,0
    - service: light.turn_on
     entity: light.dining_room_right
     data:
       brightness: 255
       rgb_color: 255,0,0
   - delay:
       seconds: 3
   - service: light.turn_on
     entity: light.dining_room_right
     data:
       brightness: 255
       rgb_color: 0,255,0
   - service: light.turn_on
     entity: light.dining_room_left
     data:
       brightness: 255
       rgb_color: 255,0,0
       
