- alias: ramones
  hide_entity: True
  trigger:
    platform: time
    at: '00:00:00'
  condition:
    condition: template
    value_template: '{{ now().month == 12 and now().day == 31 }}'
  action:
    - service: media_player.volume_mute
      entity_id: media_player.vizio_smartcast
      data: 
        is_volume_muted: true
    - service: media_player.play_media
      entity_id: media_player.party_mode
      data:
        media_content_id: "http://smrtho.us/storage/i_wanna_be_sedated.mp3"
        media_content_type: "audio/mp3" 
    - delay:
        seconds: 149
    - service: script.revert
    - service: media_player.volume_mute
      entity_id: media_player.vizio_smartcast
      data: 
        is_volume_muted: false
