- alias: Windows Open
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.windows
    from: 'closed'
    to: 'open'
  condition: 
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    service: climate.set_operation_mode
    entity_id: climate.downstairs
    data:
      operation_mode: 'eco'
 
 - alias: Windows Open
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.windows
    from: 'open'
    to: 'closed'
  condition: 
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    service: climate.set_operation_mode
    entity_id: climate.downstairs
    data:
      operation_mode: 'auto'
