- alias: Morning - Stage 2
  hide_entity: True
  trigger:
    platform: time
    after: '06:30:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.tristal
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        color_temp: 250
        brightness: 254
        transition: 1800
    - service: light.turn_on
      entity_id: light.living_room
      data:
        color_temp: 250
        brightness: 254
