- alias: Morning - Stage 1
  hide_entity: True
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.pantry
      data:
        brightness: 100
        transition: 60
    - condition: state
      entity_id: group.tristal
      state: 'home'
    - condition: state
      entity_id: light.master_bedroom
      state: 'off'
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        color_temp: 500
        brightness: 50
        transition: 60
