alias: Morning - Stage 3
hide_entity: True
trigger:
  platform: time
  after: '11:00:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: light.turn_off
  entity_id: group.master_bedroom
