- alias: Color Temp Fix - Master Bedroom - Morning
  hide_entity: True
  trigger:
    - platform: state
      entity_id: group.master_bedroom
      to: 'on'
    - platform: state
      entity_id: sensor.color_temp_br
      state: '278'
  condition:
    condition: time
    after: '05:00:00'
    before: '09:30:00'
  action:
    service: light.turn_on
    entity_id: group.master_bedroom
    data:
      color_temp: 250
