- alias: Color Temp Fix - Livingroom
  hide_entity: True
  trigger:
    - platform: state
      entity_id: light.living_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.color_temp_lr
      state: '[0.402, 0.3768]'
  condition: 
    condition: template
    value_template: >
       {% if (states.sensor.time.state | round(2)) < 05.00 and states.light.floor_lamp_right.attributes.color_temp != 500 %}
          false
        {% elif (states.sensor.time.state | round(2)) < 09.50 and (states.sensor.time.state | round(2)) >= 05.00 and states.light.floor_lamp_right.attributes.color_temp != 250 %}
          false
        {% elif (states.sensor.time.state | round(2)) < 22.50 and (states.sensor.time.state | round(2)) >= 9.50 and states.light.floor_lamp_right.attributes.color_temp != 366 %}
          false
        {% elif (states.sensor.time.state | round(2)) >= 22.50 and states.light.floor_lamp_right.attributes.color_temp != 500 %}
          false
        {% else %}
          true
        {% endif %}
  action:
    service: light.turn_on
    entity_id: light.living_room
    data_template:
      color_temp: >
        {% if (states.sensor.time.state | round(2)) < 05.00 %}
          500
        {% elif (states.sensor.time.state | round(2)) < 09.50 %}
          250
        {% elif (states.sensor.time.state | round(2)) <= 22.49 %}
          366
        {% elif (states.sensor.time.state | round(2)) >= 22.50 %}
          500
        {% else %}
        {% endif %}

- alias: Color Temp Fix - Bedroom
  hide_entity: True
  trigger:
    - platform: state
      entity_id: light.master_bedroom
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.color_temp_br
      state: '[0.402, 0.3768]'
  condition: 
    condition: template
    value_template: >
       {% if (states.sensor.time.state | round(2)) < 05.00 and states.light.tristans_nightstand.attributes.color_temp != 500 %}
          false
        {% elif (states.sensor.time.state | round(2)) < 09.50 and (states.sensor.time.state | round(2)) >= 05.00 and states.light.tristans_nightstand.attributes.color_temp != 250 %}
          false
        {% elif (states.sensor.time.state | round(2)) < 22.50 and (states.sensor.time.state | round(2)) >= 9.50 and states.light.tristans_nightstand.attributes.color_temp != 366 %}
          false
        {% elif (states.sensor.time.state | round(2)) >= 22.50 and states.light.tristans_nightstand.attributes.color_temp != 500 %}
          false
        {% else %}
          true
        {% endif %}
  action:
    service: light.turn_on
    entity_id: light.master_bedroom
    data_template:
      color_temp: >
        {% if (states.sensor.time.state | round(2)) <= 05.00 %}
          500
        {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
          250
        {% elif (states.sensor.time.state | round(2)) <= 22.49 %}
          366
        {% elif (states.sensor.time.state | round(2)) >= 22.50 %}
          500
        {% else %}
        {% endif %}


- alias: Color Temp Fix - Cabinet Lights
  hide_entity: True
  trigger:
    - platform: state
      entity_id: light.cabinet_lights
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.color_temp_cl
      state: '[0.402, 0.3768]'
  condition:
    - condition: or
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: sensor.color_temp_cl
          state: '[0.402, 0.3768]'
    - condition: template
      value_template: >
         {% if (states.sensor.time.state | round(2)) < 05.00 and states.light.cabinet_lights.attributes.color_temp != 450 %}
            false
          {% elif (states.sensor.time.state | round(2)) < 09.50 and (states.sensor.time.state | round(2)) >= 05.00 and states.light.cabinet_lights.attributes.color_temp != 250 %}
            false
          {% elif (states.sensor.time.state | round(2)) < 22.50 and (states.sensor.time.state | round(2)) >= 9.50 and states.light.cabinet_lights.attributes.color_temp != 366 %}
            false
          {% elif (states.sensor.time.state | round(2)) >= 22.50 and states.light.cabinet_lights.attributes.color_temp != 450 %}
            false
          {% else %}
            true
          {% endif %}        
  action:
    service: light.turn_on
    entity_id: light.cabinet_lights
    data_template:
      color_temp: >
        {% if (states.sensor.time.state | round(2)) <= 05.00 %}
          450
        {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
          250
        {% elif (states.sensor.time.state | round(2)) <= 22.49 %}
          300
        {% elif (states.sensor.time.state | round(2)) >= 22.50 %}
          450
        {% else %}
        {% endif %}
