- alias: Color Temp Fix - Living Room - Morning
  hide_entity: True
  trigger:
    - platform: state
      entity_id: group.living_room_lights
      to: 'on'
    - platform: state
      entity_id: sensor.color_temp_lr
      state: '278'
  condition:
    condition: time
    after: '05:00:00'
    before: '09:30:00'
  action:
    service: light.turn_on
    entity_id: group.living_room_lights
    data:
      color_temp: 250
