- alias: lock on close front door
  hide_entity: true
  trigger: 
    platform: state
    entity_id: sensor.front_door
    from: 'Open'
    to: 'Closed'
  condition:
    condition: state
    entity_id: input_boolean.front_door_open
    state: 'on'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.all_assistants
      data:
        message: 'Locking the front door.'
    - service: lock.lock
      entity_id: lock.front_door

- alias: lock on close back door
  hide_entity: true
  trigger: 
    platform: state
    entity_id: sensor.back_door
    from: 'Open'
    to: 'Closed'
  condition:
    condition: state
    entity_id: input_boolean.back_door_open
    state: 'on'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.all_assistants
      data:
        message: 'Locking the back door.'
    - service: lock.lock
      entity_id: lock.back_door

- alias: input_boolean off
  hide_entity: True
  trigger:
    platform: state
    entity_id:
      - input_boolean.front_door_open
      - input_boolean.back_door_open
    to: 'on'
    for:
      minutes: 10
  action:
    service: input_boolean.turn_off
    entity_id:
      - input_boolean.front_door_open
      - input_boolean.back_door_open
      
