- alias: lock on close - front door
  hide_entity: true
  trigger: 
    platform: state
    entity_id: sensor.front_door
    from: 'open'
    to: 'closed'
  condition:
    condition: state
    entity_id: input_boolean.front_door_open
    state: 'on'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.downstairs
        - media_player.google_home_2
      data:
        message: 'Locking the front door.'
    - service: switch.turn_on
      entity_id: switch.door_front

- alias: lock on close - back door
  hide_entity: true
  trigger: 
    platform: state
    entity_id: sensor.back_door
    from: 'open'
    to: 'closed'
  condition:
    condition: state
    entity_id: input_boolean.back_door_open
    state: 'on'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.downstairs
        - media_player.google_home_2
      data:
        message: 'Locking the back door.'
    - service: switch.turn_on
      entity_id: switch.door_rear

- alias: input_boolean off
  hide_entity: True
  trigger:
    platform: state
    entity_id:
      - input_boolean.front_door_open
      - input_boolean.back_door_open
    state: 'on'
    for:
      minutes: 10
  action:
    service: input_boolean.turn_off
    entity_id:
      - input_boolean.front_door_open
      - input_boolean.back_door_open
      
