- alias: Morning Stage 4
  trigger:
    platform: time
    at: '9:30:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room_lights
      state: 'on'
    - condition: template
      value_template: '{{ states.light.living_room_lights.attributes.color_temp == 200 }}'
  action:
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        color_temp: 300
        brightness: 254
        transition: 1800
    - condition: state
      entity_id: light.master_bedroom
      state: 'on'
    - service: light.turn_on  
      entity_id: light.master_bedroom
      data:
        color_temp: 300
        brightness: 254
        transition: 1800
