- platform: mqtt
  name: "Ring Doorbell"
  state_topic: "smartthings/Front Door/button"
  qos: 0
  payload_on: "pushed"
  payload_off: "default"
  sensor_class: occupancy
- platform: mqtt
  name: "Front Door Motion"
  state_topic: "smartthings/Front Door/motion"
  qos: 0
  payload_on: "active"
  payload_off: "inactive"
  sensor_class: motion
- platform: rest
  name: Front Doors
  resource: http://10.0.0.7:8123/api/states/binary_sensor.front_door
  sensor_class: opening
  value_template: "{{ value_json.state. }}"
- platform: rest
  name: Garage Door
  resource: http://10.0.0.7:8123/api/states/binary_sensor.garage_door
  sensor_class: opening
  value_template: "{{ value_json.state. }}"
- platform: rest
  name: Back Door
  resource: http://10.0.0.7:8123/api/states/binary_sensor.back_door
  sensor_class: opening
  value_template: "{{ value_json.state. }}"
- platform: rest
  name: Front Windows
  resource: http://10.0.0.7:8123/api/states/binary_sensor.front_windows
  sensor_class: opening
  value_template: "{{ value_json.state. }}"
- platform: rest
  name: Back Windows
  resource: http://10.0.0.7:8123/api/states/binary_sensor.back_windows
  sensor_class: opening
  value_template: "{{ value_json.state. }}"
- platform: rest
  name: Bedroom Windows
  resource: http://10.0.0.7:8123/api/states/binary_sensor.bedroom_windows
  sensor_class: opening
  value_template: "{{ value_json.state. }}"
