- platform: rpi_gpio
  ports:
    18: Front Door
    6: Front Windows
    27: Garage Door
    4: Back Door
    22: Back Windows
    17: Bedroom Windows
- platform: mqtt
  name: "Ring Doorbell"
  state_topic: "smartthings/Front Door/button"
  qos: 0
  payload_on: "pushed"
  payload_off: "default"
  sensor_class: occupancy
- platform: mqtt
  name: "Front Door Motion"
  state_topic: "smartthings/Front Door/motion"
  qos: 0
  payload_on: "active"
  payload_off: "inactive"
  sensor_class: motion
