- platform: template
  sensors:
    rain:
      value_template: '{{ states.sensor.dark_sky_icon.state == "rain"}}'
- platform: mqtt
  name: Bedroom Windows
  state_topic: "gpio/input/Bedroom Windows"
  payload_on: "OPEN"
  payload_off: "CLOSED"
- platform: mqtt
  name: Front Windows
  state_topic: "gpio/input/Front Windows"
  payload_on: "OPEN"
  payload_off: "CLOSED"
- platform: mqtt
  name: Back Windows
  state_topic: "gpio/input/Back Windows"
  payload_on: "OPEN"
  payload_off: "CLOSED"
- platform: mqtt
  name: Front Door
  state_topic: "gpio/input/Front Door"
  payload_on: "OPEN"
  payload_off: "CLOSED"
- platform: mqtt
  name: Back Door
  state_topic: "gpio/input/Back Door"
  payload_on: "OPEN"
  payload_off: "CLOSED"
- platform: mqtt
  name: Garage Door
  state_topic: "gpio/input/Garage Door"
  payload_on: "OPEN"
  payload_off: "CLOSED"
- platform: template
  sensors:
    virtual_dark:
      friendly_name: "Virtually Dark"
      delay_on:
        seconds: 60
      delay_off:
        seconds: 60
      value_template: >
        {% if ( (states.sun.sun.attributes.elevation | int < 10) and (states.sensor.dark_sky_cloud_coverage.state | int > 30)) %}true
        {% elif ( (states.sun.sun.attributes.elevation | int < 15) and (states.sensor.dark_sky_cloud_coverage.state | int > 45)) %}true
        {% elif ( (states.sun.sun.attributes.elevation | int < 20) and (states.sensor.dark_sky_cloud_coverage.state | int > 70)) %}true
        {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %}true
        {% else %}false
          {% endif %}
