#- platform: bluetooth_tracker
#  track_new_devices: false
#  consider_home: 180
#- platform: bluetooth_le_tracker
#- platform: asuswrt
#  host: 10.0.0.1
#  protocol: telnet
#  mode: router
#  username: !secret router_user
#  password: !secret router_pass
#  track_new_devices: false
#  consider_home: 180
- platform: google_maps
  username: !secret maps_user
  password: !secret maps_pass
