- platform: bluetooth_le_tracker
  track_new_devices: false
  interval_seconds: 1
  consider_home: 300
- platform: asuswrt
  host: 10.0.0.1
  protocol: ssh
  mode: router
  username: !secret router_user
  password: !secret router_pass
  track_new_devices: false
  consider_home: 300
