sensor:
  - platform: google_travel_time
    name: Drive_time_to_work
    api_key: AIzaSyBf2VtYWJ9-F-2T78pRq-YcnE8vTxrc9jk
    origin: place_id:ChIJG1SUhnKff4gRz9_GI6GdfUY
    destination: place_id:ChIJkRB9LrKFf4gRgqu8ivoA0x8
    options:
      arrival_time: '10:15:00'
    
