- platform: hue
  host: 10.0.0.208
  allow_unreachable: true
- platform: mqtt
  lights:  
    christmas_lights:
      name: 'Christmas Lights'
      state_topic: "smartthings/Christmas Lights/switch"
      command_topic: "smartthings/Christmas Lights/switch"
      payload_on: "on"
      payload_off: "off"
      retain: true
 #   overhead_light:
 #     name: 'Overhead Light'
 #     state_topic: "smartthings/Overhead Light/switch"
 #     command_topic: "smartthings/Overhead Light/switch"
 #     payload_on: "on"
 #     payload_off: "off"
 #     retain: true
 #   recessed_lights:
 #     name: 'Recessed Lights'
 #     state_topic: "smartthings/Recessed Lights/switch"
 #     command_topic: "smartthings/Recessed Lights/switch"
 #     brightness_scale: 100
 #     brightness_state_topic: "smartthings/Recessed Lights/level"
 #     brightness_command_topic: "smartthings/Recessed Lights/level"
 #     payload_on: "on"
 #     payload_off: "off"
 #     retain: true
 #   chandelier:
 #     name: 'Chandelier'
 #     state_topic: "smartthings/Chandelier/switch"
 #     command_topic: "smartthings/Chandelier/switch"
 #     payload_on: "on"
 #     payload_off: "off"
 #     retain: true
 #   fan:
 #     name: 'Fan'
 #     state_topic: "smartthings/Fan/switch"
 #     command_topic: "smartthings/Fan/switch"
 #     brightness_scale: 100
 #     brightness_state_topic: "smartthings/Fan/level"
 #     brightness_command_topic: "smartthings/Fan/level"
 #     payload_on: "on"
 #     payload_off: "off"
 #     retain: true
