#- platform: group
#  name: Front Floods
#  entities: 
#    - light.front_flood_1
#    - light.front_flood_2
#- platform: group
#  name: Rear Floods
#  entities: 
#    - light.rear_flood_1
#    - light.rear_flood_2
#- platform: group
#  name: Flood Lights
#  entities: 
#    - light.front_flood_1
#    - light.front_flood_2 
#    - light.rear_flood_1
#    - light.rear_flood_2
- platform: osramlightify
  host: 10.0.0.214
  allow_lightify_groups: true
