- platform: osramlightify
  host: 10.0.0.214
  allow_lightify_groups: true
- platform: group
  name: Front Floods
  entities:
    - light.front_flood_light_1
    - light.front_flood_light_2
- platform: group
  name: Rear Floods
  entities:
    - light.rear_flood_light_1
    - light.rear_flood_light_2
- platform: group
  name: Flood Lights
  entities:
    - light.front_floods
    - light.rear_floods
- platform: group
  name: Mancave Lights
  entities:
    - light.desk_lamp
    - light.man_cave_floor_lamp
    - light.desk_light
light:
  - platform: switch
    name: Desk Light
    entity_id: switch.desk_light
