- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Bedroom DirecTV
  device: 88F7C7A17C19
- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Livingroom DirecTV
  device: 347A60F399D9
- platform: vizio
  host: 10.0.0.150
  access_token: !secret vizio_access_token_livingroom_tv
- platform: vizio
  host: 10.0.0.63
  access_token: !secret vizio_access_token_bedroom_tv

