- platform: cast
- platform: plex
  scan_interval: 10
- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Mancave DirecTV
  device: 0
- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Livingroom DirecTV
  device: 00367694C1C4
- platform: vizio
  host: 10.0.0.93
  access_token: Zebdyu99si

