- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Bedroom DirecTV
  device: 88F7C7A17C19
- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Livingroom DirecTV
  device: 347A60F399D9
- platform: vizio
  name: vizio_smartcast
  host: 10.0.0.150
  access_token: !secret vizio_access_token_livingroom_tv
- platform: vizio
  name: vizio_smartcast_2
  host: 10.0.0.63
  access_token: !secret vizio_access_token_bedroom_tv
- platform: androidtv
  name: Mi Box S
  host: 10.0.0.55
  apps: {'com.google.android.youtube.tvunplugged': 'Youtube TV'}
  state_detection_rules: 
    'com.plexapp.android':
      - 'media_session_state'
    'com.turner.cnvideoapp':
      - 'media_session_state'
    'com.google.android.youtube.tvunplugged':
      - 'media_session_state'
    'com.hulu.livingroomplus':
      - 'media_session_state'
    'com.google.android.tvlauncher':
      - 'standby'
    
    
