- platform: plex
  scan_interval: 5
  show_all_controls: false
  use_episode_art: true
  remove_unavailable_clients: true
  client_remove_interval: 600
- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Mancave DirecTV
  device: 88F7C7A17C19
- platform: directv
  host: 10.0.0.151
  port: 8080
  name: Livingroom DirecTV
  device: 347A60F399D9
- platform: vizio
  host: 10.0.0.150
  access_token: !secret vizio_access_token_livingroom_tv
- platform: vizio
  host: 10.0.0.63
  access_token: !secret vizio_access_token_bedroom_tv

