- platform: cast
- platform: plex
  scan_interval: 10
  - platform: directv
    host: 10.0.0.151
    port: 8080
    name: MANCAVE
    device: 0
  - platform: directv
    host: 10.0.0.151
    port: 8080
    name: LIVINGROOM
    device: 00367694C1C4
