- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - icon
    - summary
    - precip_intensity
    - precip_probability
#    - precip_type
    - temperature
    - temperature_max
    - temperature_min
- platform: google_travel_time
  name: Drive_time_to_work
  api_key: AIzaSyBf2VtYWJ9-F-2T78pRq-YcnE8vTxrc9jk
  origin: place_id:ChIJG1SUhnKff4gRz9_GI6GdfUY
  destination: place_id:ChIJkRB9LrKFf4gRgqu8ivoA0x8
  options:
    arrival_time: '09:15:00'
- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
    brightness_pntry:
      value_template: '{{ states.light.pantry.attributes.brightness }}'
    brightness_lr:
      value_template: '{{ states.light.living_room.attributes.brightness }}'
    color_temp_lr:
      value_template: '{{ states.light.living_room.attributes.xy_color }}'
    color_temp_br:
      value_template: '{{ states.light.master_bedroom.attributes.xy_color }}'
    color_temp_cl:
      value_template: '{{ states.light.cabinet_lights.attributes.xy_color }}'
    time:
      value_template: '{{(now().strftime("%H") | int) + (now().strftime("%M")|int / 60) | round(2)}}'
    protect_down:
      value_template: '{% if is_state("binary_sensor.downstairs_nest_protect_online", "on") %}Online{% else %}Error{% endif %}'    
    protect_up:
      value_template: '{% if is_state("binary_sensor.upstairs_nest_protect_online", "on") %}Online{% else %}Error{% endif %}'
- platform: command_line
  name: Door Status Front
  command: "python /home/hass/.homeassistant/kevo/status-front.py"
  scan_interval: 30
- platform: command_line  
  name: Door Status Rear
  command: "python /home/hass/.homeassistant/kevo/status-rear.py"
  scan_interval: 30
- platform: rest
  name: Front Door
  resource: http://10.0.0.7:8123/api/states/binary_sensor.front_door
  sensor_class: opening
  value_template: "{{ value_json.state }}"
- platform: rest
  name: Garage Door
  resource: http://10.0.0.7:8123/api/states/binary_sensor.garage_door
  sensor_class: opening
  value_template: "{{ value_json.state }}"
- platform: rest
  name: Back Door
  resource: http://10.0.0.7:8123/api/states/binary_sensor.back_door
  sensor_class: opening
  value_template: "{{ value_json.state }}"
- platform: rest
  name: Front Windows
  resource: http://10.0.0.7:8123/api/states/binary_sensor.front_windows
  sensor_class: opening
  value_template: "{{ value_json.state }}"
- platform: rest
  name: Back Windows
  resource: http://10.0.0.7:8123/api/states/binary_sensor.back_windows
  sensor_class: opening
  value_template: "{{ value_json.state }}"
- platform: rest
  name: Bedroom Windows
  resource: http://10.0.0.7:8123/api/states/binary_sensor.bedroom_windows
  sensor_class: opening
  value_template: "{{ value_json.state }}"
#- platform: command_line
#  name: CPU Temperature
#  command: "cat /sys/class/thermal/thermal_zone0/temp"
#  value_template: '{{ value | multiply(0.0018) | round(1) +32 }}'
#  unit_of_measurement: "°F"
#- platform: systemmonitor
#  resources:
#    - type: disk_use_percent
#      arg: /
#    - type: memory_use_percent
#    - type: processor_use
