#- platform: wunderground
#  api_key: 1e3e716e93f82a3c
#  monitored_conditions:
#    - alerts
#    - weather_1d
#    - precip_1d
- platform: time_date
  display_options:
    - 'time'
- platform: darksky
  api_key: !secret darksky
  latitude: !secret latitude
  longitude: !secret longitude
  monitored_conditions:
    - icon
    - daily_summary
    - summary
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - cloud_cover
    - uv_index
- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      entity_id: remote.livingroom
      value_template: >
        {% if states.remote.livingroom.attributes.current_activity == null%}
          'Unknown'
        {% else %}
          {{states.remote.livingroom.attributes.current_activity}}
        {% endif %}
    brightness_pantry:
      entity_id: light.pantry
      value_template: >
        {% if states.light.pantry.state == 'off'%}
          0
        {% else %}
          {{states.light.pantry.attributes.brightness}}
        {% endif %}
    brightness_lr:
      entity_id: light.living_room
      value_template: '{{ states.light.living_room.attributes.brightness }}'
    decimal_time:
      entity_id: sensor.time
      value_template: '{{(now().strftime("%H") | int) + (now().strftime("%M")|int / 60) | round(2)}}'
    protect_down:
      entity_id: sensor.downstairs_nest_protect_bedroom_battery_heath
      value_template: '{% if  states.sensor.downstairs_nest_protect_bedroom_battery_health.state == "Ok" and states.sensor.downstairs_nest_protect_bedroom_co_status.state == "Ok" and states.sensor.downstairs_nest_protect_bedroom_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_bedroom_co_status.state == "Emergency" or states.sensor.downstairs_nest_protect_bedroom_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.downstairs_nest_protect_bedroom_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'    
    protect_kitchen:
      entity_id: sensor.downstairs_nest_protect_kitchen_battery_health
      value_template: '{% if  states.sensor.downstairs_nest_protect_kitchen_battery_health.state == "Ok" and states.sensor.downstairs_nest_protect_kitchen_co_status.state == "Ok" and states.sensor.downstairs_nest_protect_kitchen_smoke_status.state == "Ok" %}Online{% elif states.sensor.downstairs_nest_protect_kitchen_co_status.state == "Emergency" or states.sensor.downstairs_nest_protect_kitchen_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.downstairs_nest_protect_kitchen_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'
    protect_up:
      entity_id: sensor.upstairs_nest_protect_hallway_battery_health
      value_template: '{% if  states.sensor.upstairs_nest_protect_hallway_battery_health.state == "Ok" and states.sensor.upstairs_nest_protect_hallway_co_status.state == "Ok" and states.sensor.upstairs_nest_protect_hallway_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_hallway_co_status.state == "Emergency" or states.sensor.upstairs_nest_protect_hallway_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.upstairs_nest_protect_hallway_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'      
    front_door:
      entity_id: binary_sensor.front_door
      friendly_name: 'Front Door'
      value_template: '{% if is_state("binary_sensor.front_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_door", "off") %}mdi:door{% else %}mdi:door-open{% endif %}'
    back_door:
      entity_id: binary_sensor.back_door
      friendly_name: 'Back Door'
      value_template: '{% if is_state("binary_sensor.back_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_door", "off") %}mdi:door{% else %}mdi:door-open{% endif %}'
    garage_door:
      entity_id: binary_sensor.garage_door
      friendly_name: 'Garage Door'
      value_template: '{% if is_state("binary_sensor.garage_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.garage_door", "off") %}mdi:door{% else %}mdi:door-open{% endif %}'
    front_windows:
      entity_id: binary_sensor.front_windows
      friendly_name: 'Front Windows'
      value_template: '{% if is_state("binary_sensor.front_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    back_windows:
      entity_id: binary_sensor.back_windows
      friendly_name: 'Back Windows'
      value_template: '{% if is_state("binary_sensor.back_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    bedroom_windows:
      entity_id: binary_sensor.bedroom_windows
      friendly_name: 'Bedroom Windows'
      value_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    downstairs_windows:
      entity_id:
        - binary_sensor.back_windows
        - binary_sensor.front_windows
      friendly_name: 'Back Windows'
      value_template: '{% if states.binary_sensor.back_windows.state == "off" and states.binary_sensor.front_windows.state == "off" %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if states.binary_sensor.back_windows.state == "off" and states.binary_sensor.front_windows.state == "off" %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    huebridge:
      entity_id: device_tracker.huebridge
      value_template: '{% if is_state("device_tracker.huebridge", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Hue Bridge'
    harmonyhub:
      entity_id: device_tracker.harmonyhub
      value_template: '{% if is_state("device_tracker.harmonyhub", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Harmony Hub'
    smartthingshub:
      entity_id: device_tracker.smartthingshub
      value_template: '{% if is_state("device_tracker.smartthingshub", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'SmartThings Hub'
    myq:
      entity_id: device_tracker.myq
      value_template: '{% if is_state("device_tracker.myq", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'MyQ Bridge'
    macmini:
      entity_id: device_tracker.macmini
      value_template: '{% if is_state("device_tracker.macmini", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Mac Mini'
    directv_genie:
      entity_id: device_tracker.directv_genie
      value_template: '{% if is_state("device_tracker.directv_genie", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'DirecTv Genie'
    google_home_livingroom:
      entity_id: device_tracker.google_home_livingroom
      value_template: '{% if is_state("device_tracker.google_home_livingroom", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home (Livingroom)' 
    google_home_mini_mancave:
      entity_id: device_tracker.google_home_mini_mancave
      value_template: '{% if is_state("device_tracker.google_home_mini_mancave", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Mancave)' 
    google_home_mini_nursery:
      entity_id: device_tracker.google_home_mini_nursery
      value_template: '{% if is_state("device_tracker.google_home_mini_nursery", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Nursery)'       
    google_home_hub_kitchen:
      entity_id: device_tracker.google_home_hub_kitchen
      value_template: '{% if is_state("device_tracker.google_home_hub_kitchen", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Hub (Kitchen)'  
    google_home_mini_bedroom:
      entity_id: device_tracker.google_home_mini_bedroom
      value_template: '{% if is_state("device_tracker.google_home_mini_bedroom", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Bedroom)'
    google_home_mini_bathroom:
      entity_id: device_tracker.google_home_mini_bathroom
      value_template: '{% if is_state("device_tracker.google_home_mini_bathroom", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Bathroom)' 
    chromecast_man_cave:
      entity_id: device_tracker.chromecast_man_cave
      value_template: '{% if is_state("device_tracker.chromecast_man_cave", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Chromecast (Mancave)'
    chromecast_audio_dining_room:
      entity_id: device_tracker.chromecast_audio_dining_room
      value_template: '{% if is_state("device_tracker.chromecast_audio_dining_room", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Chromecast Audio (Dining Room)'
    chromecast_audio_garage:
      entity_id: device_tracker.chromecast_audio_garage
      value_template: '{% if is_state("device_tracker.chromecast_audio_garage", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Chromecast Audio (Garage)'  
    viziocrave360:
      entity_id: device_tracker.viziocrave360
      value_template: '{% if is_state("device_tracker.viziocrave360", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Vizio Crave 360' 
    vizio_m70e3:
      entity_id: device_tracker.vizio_m70e3
      value_template: '{% if is_state("device_tracker.vizio_m70e3", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Vizio M70'
    lg_sj9:
      entity_id: device_tracker.lg_sj9
      value_template: '{% if is_state("device_tracker.lg_sj9", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'LG SJ9' 
    rasplex:
      entity_id: device_tracker.rasplex
      value_template: '{% if is_state("device_tracker.rasplex", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'RasPlex'
    nesthello:
      entity_id: device_tracker.nest_hello
      value_template: '{% if is_state("device_tracker.nest_hello", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Nest Hello'
    lightifybridge:
      entity_id: device_tracker.lightify_bridge
      value_template: '{% if is_state("device_tracker.lightify_bridge", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Lightify Bridge'
    away_toggle:
      entity_id: input_boolean.disable_away_mode
      value_template: '{% if is_state("input_boolean.disable_away_mode", "on") %}home{% else %}not_home{% endif %}'
      friendly_name: 'Away Toggle'    
    hvac_leak_sensor:
      entity_id: binary_sensor.hvac_leak_sensor
      value_template: '{% if is_state("binary_sensor.hvac_leak_sensor", "off") %}Dry{% elif is_state("binary_sensor.hvac_leak_sensor", "on") %}Wet{% endif %}'
      icon_template: '{% if is_state("binary_sensor.hvac_leak_sensor", "off") %}mdi:water-off{% elif is_state("binary_sensor.hvac_leak_sensor", "on") %}mdi:water{% endif %}'
      friendly_name: 'HVAC Leak Sensor'
    water_heater_leak_sensor:
      entity_id: binary_sensor.water_heater_leak_sensor
      value_template: '{% if is_state("binary_sensor.water_heater_leak_sensor", "off") %}Dry{% elif is_state("binary_sensor.water_heater_leak_sensor", "on") %}Wet{% endif %}'
      icon_template: '{% if is_state("binary_sensor.water_heater_leak_sensor", "off") %}mdi:water-off{% elif is_state("binary_sensor.water_heater_leak_sensor", "on") %}mdi:water{% endif %}'
      friendly_name: 'Water Heater Leak Sensor' 
    tautulli_streams:
      entity_id: sensor.tautulli
      value_template: '{{ states.sensor.tautulli.attributes.stream_count }}'
      icon_template: mdi:cloud-upload-outline
      friendly_name: 'Streams'
      unit_of_measurement: ' '
    tautulli_transcodes:
      entity_id: sensor.tautulli
      value_template: '{{ states.sensor.tautulli.attributes.stream_count_transcode }}'
      icon_template: mdi:cloud-upload
      friendly_name: 'Transcodes'
      unit_of_measurement: ' '
    ender_3_pro_print_time_remaining:
      value_template: >
        {% set minutes = (states.sensor.ender_3_pro_time_remaining.state|int/60) | int %}{% set hours = (minutes/60) |int %}{% set minutes = minutes-(hours*60)%}{% set seconds = states.sensor.ender_3_pro_time_remaining.state|int - (minutes*60) - ((hours*60)*60) %}{%if hours==0 %}{% elif hours==1%}{{hours}} hour, {% else %}{{hours}} hours, {% endif %}{%if minutes==0 %}{% elif minutes==1%}{{minutes}} minute{% else %}{{minutes}} minutes{% endif %}{% if hours == 0 and minutes == 0 and seconds > 30 %}Less than a minute{%elif hours == 0 and minutes == 0 and seconds == 0 and states.sensor.ender_3_pro_print_job_percentage.state == "100"%}Print Complete{%elif states.sensor.ender_3_pro_time_remaining.state == "unknown" %}Calculating...{%elif hours == 0 and minutes == 0 and seconds <= 30 and states.sensor.ender_3_pro_time_remaining != "unknown" %}A few seconds{%endif%}
      friendly_name: 'Time Remaining'
    ender_3_pro_print_job_percentage:
      entity_id: sensor.ender_3_pro_job_percentage
      value_template: '{{ states.sensor.ender_3_pro_job_percentage.state|int }}'
      friendly_name: 'Job Progress'
      unit_of_measurement: '%'      
    mp_select_mini_print_time_remaining:
      value_template: >
        {% set minutes = (states.sensor.mp_select_mini_time_remaining.state|int/60) | int %}{% set hours = (minutes/60) |int %}{% set minutes = minutes-(hours*60)%}{% set seconds = states.sensor.mp_select_mini_time_remaining.state|int - (minutes*60) - ((hours*60)*60) %}{%if hours==0 %}{% elif hours==1%}{{hours}} hour, {% else %}{{hours}} hours, {% endif %}{%if minutes==0 %}{% elif minutes==1%}{{minutes}} minute{% else %}{{minutes}} minutes{% endif %}{% if hours == 0 and minutes == 0 and seconds > 30 %}Less than a minute{%elif hours == 0 and minutes == 0 and seconds == 0 and states.sensor.mp_select_mini_print_job_percentage.state == "100"%}Print Complete{%elif states.sensor.mp_select_mini_time_remaining.state == "unknown" %}Calculating...{%elif hours == 0 and minutes == 0 and seconds <= 30 and states.sensor.mp_select_mini_time_remaining != "unknown" %}A few seconds{%endif%}
      friendly_name: 'Time Remaining'
    mp_select_mini_print_job_percentage:
      entity_id: sensor.mp_select_mini_job_percentage
      value_template: '{{ states.sensor.mp_select_mini_job_percentage.state|int }}'
      friendly_name: 'Job Progress'
      unit_of_measurement: '%'       
- platform: random
  name: whitenoise
  minimum: 1
  maximum: 8
- platform: mqtt
  state_topic: "plex"
  name: "Rasplex Status"
  value_template: '{{ value_json.body }}'
- platform: mqtt
  state_topic: smartthings/Water Heater Leak Sensor/temperature
  name: "Small Attic Temp"
  unit_of_measurement: '°F'
- platform: mqtt
  state_topic: smartthings/Water Heater Leak Sensor/battery
  name: "WH water sensor battery"
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: smartthings/HVAC Leak Sensor/temperature
  name: "Big Attic Temp"
  unit_of_measurement: '°F'
- platform: mqtt
  state_topic: smartthings/Back Door/battery
  name: "Back Door Lock Battery"
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: smartthings/Front Door/battery
  name: "Front Door Lock Battery"
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: smartthings/HVAC Leak Sensor/battery
  name: "HVAC water sensor battery"
  unit_of_measurement: '%'
- platform: dnsip
  scan_interval: 300
- platform: rest
  resource: http://10.0.0.109:61208/api/3/quicklook/cpu
  name: "CPU Usage"
  value_template: '{{ value_json.cpu }}'
  unit_of_measurement: '%'
  scan_interval: 3
- platform: rest
  resource: http://10.0.0.109:61208/api/3/mem/percent
  name: "Memory Usage"
  value_template: '{{ value_json.percent }}'
  unit_of_measurement: '%'
  scan_interval: 3
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 0
  value_template: '{{ value_json[0].percent| round(1) }}'
  unit_of_measurement: '%'  
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 1
  value_template: '{{ value_json[1].percent| round(1) }}'
  unit_of_measurement: '%'  
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 2
  value_template: '{{ value_json[2].percent| round(1) }}'
  unit_of_measurement: '%'
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 3
  value_template: '{{ value_json[3].percent| round(1) }}'
  unit_of_measurement: '%'
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 4
  value_template: '{{ value_json[4].percent| round(1) }}'
  unit_of_measurement: '%'
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 5
  value_template: '{{ value_json[5].percent| round(1) }}'
  unit_of_measurement: '%'
- platform: rest
  resource: http://10.0.0.109:61208/api/3/fs
  name: Disk 6 
  value_template: '{{ value_json[6].percent| round(1) }}'
  unit_of_measurement: '%'    
- platform: tautulli
  api_key: 06c026da13d149308c932cba8c771bc4
  host: 10.0.0.109
  scan_interval: 5
- platform: pi_hole
  host: 10.0.0.3
#- platform: command_line
#  name: Download
#  scan_interval:
#    minutes: 30
#  command: 'ssh titan@10.0.0.110 | speedtest --server 5109 --json --no-upload'
#  value_template: '{{(value_json.download/1048576) | round(2)}}'
#- platform: command_line
#  name: air_quality
#  scan_interval:
#    minutes: 10
#  command: 'curl -X GET -H "Content-type: application/json" -H "Accept: application/json" "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=38016&distance=25&API_KEY=BB4DF57E-645A-4867-935F-3BC241441002"'
#  value_template: '{{value_json[0]["AQI"]}}'
