- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - icon
    - summary
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_max
    - temperature_min
- platform: google_travel_time
  name: Drive_time_to_work
  api_key: AIzaSyBf2VtYWJ9-F-2T78pRq-YcnE8vTxrc9jk
  origin: place_id:ChIJG1SUhnKff4gRz9_GI6GdfUY
  destination: place_id:ChIJkRB9LrKFf4gRgqu8ivoA0x8
  options:
    arrival_time: '09:15:00'
- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.living_room_2.attributes.current_activity }}'
    brightness_pntry:
      value_template: '{{ states.light.pantry.attributes.brightness }}'
    brightness_lr:
      value_template: '{{ states.light.living_room_2.attributes.brightness }}'
    color_temp_lr:
      value_template: '{{ states.light.living_room_2.attributes.xy_color }}'
    color_temp_br:
      value_template: '{{ states.light.master_bedroom_2.attributes.xy_color }}'
    color_temp_cl:
      value_template: '{{ states.light.cabinet_lights.attributes.xy_color }}'
    time:
      value_template: '{{(now().strftime("%H") | int) + (now().strftime("%M")|int / 60) | round(2)}}'
    protect_down:
      value_template: '{% if is_state("binary_sensor.downstairs_nest_protect_online", "on") %}Online{% else %}Error{% endif %}'    
    protect_up:
      value_template: '{% if is_state("binary_sensor.upstairs_nest_protect_online", "on") %}Online{% else %}Error{% endif %}'
    front_door:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("binary_sensor.front_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_door", "off") %}mdi:crop-portrait{% else %}mdi:logout{% endif %}'
    back_door:
      friendly_name: 'Back Door'
      value_template: '{% if is_state("binary_sensor.back_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_door", "off") %}mdi:crop-portrait{% else %}mdi:logout{% endif %}'
    garage_door:
      friendly_name: 'Garage Door'
      value_template: '{% if is_state("binary_sensor.garage_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.garage_door", "off") %}mdi:crop-portrait{% else %}mdi:logout{% endif %}'
    front_windows:
      friendly_name: 'Front Windows'
      value_template: '{% if is_state("binary_sensor.front_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    back_windows:
      friendly_name: 'Back Windows'
      value_template: '{% if is_state("binary_sensor.back_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    bedroom_windows:
      friendly_name: 'Bedroom Windows'
      value_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
- platform: command_line
  name: Door Status Front
  command: "python /home/hass/.homeassistant/kevo/status-front.py"
  scan_interval: 30
- platform: command_line  
  name: Door Status Rear
  command: "python /home/hass/.homeassistant/kevo/status-rear.py"
  scan_interval: 30
- platform: random
  name: whitenoise
  minimum: 1
  maximum: 3
