- platform: template
  switches:
    vacation_mode:
      value_template: "{{ states.group.vacation_mode.state == 'off' }}"
      turn_on:
        service: automation.turn_off
        entity_id: group.vacation_mode
      turn_off:
        service: automation.turn_on
        entity_id: group.vacation_mode
    routines:
      value_template: "{{ states.group.disable_all_automations.state == 'off' }}"
      turn_on:
        service: automation.turn_off
        entity_id: group.disable_all_automations
      turn_off:
        - service: automation.turn_on
          entity_id: group.disable_all_automations


