- alias: Wan Down
  hide_entity: True
  trigger:
    - platform: state
      entity_id: switch.wan_down
      state: 'on'
      for:
        minutes: 20
  action:
    - service: shell_command.wan_down
    - service: switch.turn_off
      entity_id: switch.wan_down
