- alias: Simulate Presence Trigger
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.simulate_presence
  action:
    service_template: >
      {% if input_boolean.simulate_presence == 'on' %}
        homeassistant.turn_on
      {% else %}
        homeassistant.turn_off
      {% endif %}
    entity_id: group.simulate_presence

- alias: Simulate Presence 1
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 254
        transition: 900
    - service: light.turn_on
      entity_id: light.patio_lights

- alias: Simulate Presence 2
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '17:45:00'
  action:
    - delay: '00:{{ (range(0, 30)|random|int) }}:00'
    - service: light.turn_on
      entity_id:
        - light.overhead_light
        - light.recessed_lights
    
- alias: Simulate Presence 3
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '18:30:00'
  action:
    - delay: '00:{{ (range(0, 15)|random|int) }}:00'
    - service: light.turn_on
      entity_id: light.chandelier
    - delay: '00:{{ (range(0, 3)|random|int) }}:{{ (range(1,59)|random|int) }}'
    - service: light.turn_off
      entity_id: light.overhead_light
      
- alias: Simulate Presence 4
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '19:15:00'
  action:
    - delay: '00:{{ (range(0, 30)|random|int) }}:00'
    - service: light.turn_off
      entity_id: 
        - light.chandelier
        - light.recessed_lights
    - delay:
        seconds: 60
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 100
    - service: remote.turn_on
      entity_id: remote.livingroom
      data: {"activity": "Watch DirecTV"}

- alias: Simulate Presence 5
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '21:15:00'
  action:
    - delay: '00:{{ (range(0, 30)|random|int) }}:00'
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        brightness: 150
        color_temp: 500
        transition: 60
    - service: light.turn_on
      entity_id: light.desk_lamp

- alias: Simulate Presence 6
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '23:45:00'
  action:
    - delay: '00:{{ (range(0, 10)|random|int) }}:00'
    - service: remote.turn_off
      entity_id: remote.livingroom
    - delay: '00:{{ (range(0, 4)|random|int) }}:{{ (range(1,59)|random|int) }}'
    - service: light.turn_off
      entity_id: light.living_room
    - service: light.turn_off
      entity_id: light.desk_lamp
    - service: light.turn_off
      entity_id: light.patio_lights

- alias: Simulate Presence 7
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '00:05:00'
  action:
    - delay: '00:{{ (range(0, 15)|random|int) }}:00'
    - service: light.turn_off
      entity_id: light.master_bedroom
