- alias: Home Mode - Bedroom
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.tristal
    from: 'not_home'
    to: 'home'
  action:
    - service: lock.unlock
      entity_id: lock.back_door
    - service: script.master_bedroom_on
