- alias: Home Mode - Garage Hot Start
  hide_entity: true
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    to: 'open'
  condition: 
    condition: state
    entity_id: group.family
    state: 'not_home'
  action: 
    - service: automation.trigger
      entity_id: automation.home_mode__livingroom
    - service: automation.trigger
      entity_id: automation.home_mode__general
    - service: automation.trigger
      entity_id: automation.home_mode__bedroom
    - delay:
        minutes: 10
    - condition: state
      entity_id: group.tristal
      state: 'not_home'
    - service: automation.trigger
      entity_id: automation.away_mode__bedroom
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - service: automation.trigger
      entity_id: automation.away_mode__general
      
    
