- alias: Home Mode - General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  action:
    - service: climate.set_hold_mode
      entity_id: climate.downstairs
      data:
        hold_mode: 'home'
    - service: light.turn_on
      entity_id: 
        - light.pantry
        - light.recessed_lights
      data:
        brightness: 254
    - service: switch.turn_off
      entity_id: switch.door_rear
    - service: script.fan_on
    - service: media_player.turn_off
      entity_id: media_player.google_home
