- alias: Home Mode - General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  action:
    - service: climate.set_hold_mode
      entity_id: climate.downstairs
      data:
        away_mode: 'off'
    - service: light.turn_on
      entity_id: light.pantry
      data:
        brightness: 254 
    - service: media_player.turn_off
      entity_id: media_player.google_home
