- alias: Home Mode - General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  action:
    - service: climate.set_away_mode
      entity_id: climate.downstairs_hallway
      data:
        away_mode: false
    - service: light.turn_on
      entity_id: 
        - light.pantry
        - light.recessed_lights
      data:
        brightness: 254
    - service: script.fan_on
    - service: media_player.turn_off
      entity_id: media_player.livingroom_assistant
