- alias: Home Mode - Livingroom
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
        color_temp: 366
        brightness: 254
      data_template:
        color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 22.49 %}
            366
          {% elif (states.sensor.time.state | round(2)) >= 22.50 %}
            500
          {% else %}
          {% endif %}
