- alias: Home Mode - Livingroom
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 12
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 254
      data_template:
        color_temp: >
          {% if (states.sensor.time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.time.state | round(2)) <= 09.50 %}
            250
          {% elif (states.sensor.time.state | round(2)) < 22.25 %}
            366
          {% elif (states.sensor.time.state | round(2)) >= 22.25 %}
            500
          {% else %}
            366
          {% endif %}
