- alias: Home Mode Nest Hot Start Leaving Work
  trigger:
    - platform: state
      entity_id: device_tracker.google_maps_tcaulfld_gmail_com
      from: 'Sedgwick'
    - platform: state
      entity_id: device_tracker.google_maps_102616309312724957780
      from: 'TTC'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: time
      after: '15:00:00'
    - condition: template
      value_template: '{{ states.climate.downstairs_hallway.attributes.away_mode == "on" }}'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home
        structure:
          - Hidden Ridge

- alias: Home Mode Nest Hot Start Arriving Home 
  hide_entity: true
  trigger:
    platform: state
    entity_id:
      - device_tracker.google_maps_tcaulfld_gmail_com
      - device_tracker.google_maps_102616309312724957780
    from: 'not_home'
    to: 'Heading Home'
  condition:
    condition: template
    value_template: '{{ states.climate.downstairs_hallway.attributes.away_mode == "on" }}'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home
        structure:
          - Hidden Ridge

- alias: Home Mode Nest Hot Start Leaving Home 
  hide_entity: true
  trigger:
    platform: state
    entity_id:
      - device_tracker.google_maps_tcaulfld_gmail_com
      - device_tracker.google_maps_102616309312724957780
    from: 'Heading Home'
    to: 'not_home'
    for: 
      minutes: 3
  condition:
    - condition: template
      value_template: '{{ states.group.family.state == "not_home" and states.device_tracker.google_maps_102616309312724957780 != "Heading Home" and states.device_tracker.google_maps_110746778193138728717 != "Heading Home" }}'
    - condition: template
      value_template: '{{ states.climate.downstairs_hallway.attributes.away_mode == "off" }}'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: away
        structure:
          - Hidden Ridge
