- alias: Away Mode Bedroom
  trigger:
    platform: state
    entity_id: group.tristal
    from: 'home'
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: light.master_bedroom
