- alias: Away Mode - General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  action:
    - entity_id: climate.downstairs
      service: climate.set_hold_mode
      data:
        hold_mode: 'away'
    - service: media_player.turn_off
      entity_id: 
        - media_player.google_home
        - media_player.kitchen
        - media_player.downstairs
        - media_player.bedroom
        - media_player.party_mode
    - service: script.fan_off
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: media_player.volume_set
      entity_id: media_player.google_home
      data: 
        volume_level: 0.5
    - service: light.turn_off
      entity_id:
        - light.pantry
        - light.foyer
        - light.master_hallway
        - light.dining_room
        - group.stairway
        - light.overhead_light
        - light.recessed_lights
        - light.chandelier
    - service: cover.close_cover
      entity_id: cover.garage_door_opener
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if states.sun.sun.attributes.elevation <= 5 %}
            script.away_mode__night
          {% elif is_state('sensor.dark_sky_icon', 'rain') %}
            script.away_mode__rain
          {% else %}
            script.away_mode__day
          {% endif %}
    - service: script.lock_doors
    - condition: state
      entity_id: group.simulate_presence
      state: 'off'
    - service: media_player.play_media
      entity_id: media_player.google_home
      data:
        media_content_id: "http://wegr-fm.akacast.akamaistream.net/7/628/20075/v1/auth.akacast.akamaistream.net/wegr-fm"
        media_content_type: "audio/mp3"
