- alias: Away Mode - General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  action:
    - entity_id: climate.downstairs
      service: climate.set_away_mode
      data:
        away_mode: true
    - service: media_player.turn_off
      entity_id: 
        - media_player.dining_room_speaker
        - media_player.kitchen_assistant
        - media_player.livingroom_assistant
        - media_player.bedroom_speaker
        - media_player.bedroom_assistant
        - media_player.party_mode
        - media_player.all_speakers
    - service: script.fan_off
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: light.turn_off
      entity_id:
        - light.pantry
        - light.foyer
        - light.master_hallway
        - light.dining_room
        - group.stairway
        - light.overhead_light
        - light.recessed_lights
        - light.chandelier
    - service: cover.close_cover
      entity_id: cover.garage_door_opener
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if states.sun.sun.attributes.elevation <= 8 %}
            script.away_mode__night
          {% elif is_state('sensor.dark_sky_icon', 'rain') %}
            script.away_mode__rain
          {% else %}
            script.away_mode__day
          {% endif %}
    - service: script.lock_doors
