- alias: Away Mode - General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  action:
    - entity_id: climate.downstairs
      service: climate.set_away_mode
      data:
        away_mode: 'on'
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: media_player.volume_set
      entity_id: media_player.living_room_home
      data: 
        volume_level: 0.5
    - service: media_player.play_media
      entity_id: media_player.living_room_home
      data:
        media_content_id: "http://wegr-fm.akacast.akamaistream.net/7/628/20075/v1/auth.akacast.akamaistream.net/wegr-fm"
        media_content_type: "audio/mp3"
    - service: light.turn_off
      entity_id:
        - light.pantry
        - light.foyer
        - light.master_hallway
        - light.dining_room
        - group.stairway
    - service: cover.close_cover
      entity_id: cover.garage_door_opener
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if states.sun.sun.attributes.elevation <= 5 %}
            script.away_mode__night
          {% elif is_state('sensor.dark_sky_icon', 'rain') %}
            script.away_mode__rain
          {% else %}
            script.away_mode__day
          {% endif %}
    - service: script.turn_on
      entity_id: script.lock_doors
