alias: Away Mode - Night
hide_entity: True
trigger:
  platform: state
  entity_id: group.family
  from: 'home'
  to: 'not_home'
condition:
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
action:
  - entity_id: climate.downstairs
    service: climate.set_away_mode
    data:
      away_mode: 'on'
  - service: light.turn_on
    entity_id: group.living_room
    data:
      color_temp: 366
      brightness: 100
  - service: light.turn_off
    entity_id: light.pantry
  - service: remote.turn_off
    entity_id: remote.living_room
#  - service: ifttt.trigger
#    data: {"event":"PowerOff"}
